// This is automatically generated by CodeBind. Please do not modify it.

namespace ET.Client
{
    public partial class MonoUIWidgetTest
    {
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.UXText m_TestUXText;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.Button m_TestCloseButton;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.Button m_TestReopenButton;

        public UnityEngine.UI.UXText testUXText => this.m_TestUXText;
        public UnityEngine.UI.Button testCloseButton => this.m_TestCloseButton;
        public UnityEngine.UI.Button testReopenButton => this.m_TestReopenButton;

#if UNITY_EDITOR
        [Sirenix.OdinInspector.OnInspectorGUI, Sirenix.OdinInspector.PropertyOrder(-99999), Sirenix.OdinInspector.ShowIf(nameof(CheckBindDataExitEmpty))]
        private void DrawBindDataExitEmptyWarning()
        {
            Sirenix.Utilities.Editor.SirenixEditorGUI.MessageBox("BindData contains empty reference.", UnityEditor.MessageType.Warning);
        }

        private bool CheckBindDataExitEmpty()
        {
            if (this.m_TestUXText == null) return true;
            if (this.m_TestCloseButton == null) return true;
            if (this.m_TestReopenButton == null) return true;
            return false;
        }
#endif

    }
}
