//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace editor.cfg
{

public sealed partial class DRDefaultConfig :  Bright.Config.EditorBeanBase 
{
    public DRDefaultConfig()
    {
    }

    public override void LoadJson(SimpleJSON.JSONObject _json)
    {
        { 
            var _fieldJson = _json["MaxMatchTime"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  MaxMatchTime = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["Test"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  Test = _fieldJson;
            }
        }
        
    }

    public override void SaveJson(SimpleJSON.JSONObject _json)
    {
        {
            _json["MaxMatchTime"] = new JSONNumber(MaxMatchTime);
        }
        {
            _json["Test"] = new JSONNumber(Test);
        }
    }

    public static DRDefaultConfig LoadJsonDRDefaultConfig(SimpleJSON.JSONNode _json)
    {
        DRDefaultConfig obj = new DRDefaultConfig();
        obj.LoadJson((SimpleJSON.JSONObject)_json);
        return obj;
    }
        
    public static void SaveJsonDRDefaultConfig(DRDefaultConfig _obj, SimpleJSON.JSONNode _json)
    {
        _obj.SaveJson((SimpleJSON.JSONObject)_json);
    }

    /// <summary>
    /// 匹配最大时间
    /// </summary>
    public long MaxMatchTime { get; set; }

    /// <summary>
    /// 匹配最大时间
    /// </summary>
    public int Test { get; set; }

}

}