
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using SimpleJSON;
using Luban;

namespace Game.Editor
{

public sealed class DREntity :  Luban.EditorBeanBase 
{
    public DREntity()
    {
            CSName = "";
            Desc = "";
            AssetName = "";
            EntityGroupName = "";
    }

    public override void LoadJson(SimpleJSON.JSONObject _json)
    {
        { 
            var _fieldJson = _json["Id"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  Id = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["CSName"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  CSName = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["Desc"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  Desc = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["AssetName"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  AssetName = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["EntityGroupName"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  EntityGroupName = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["Priority"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  Priority = _fieldJson;
            }
        }
        
    }

    public override void SaveJson(SimpleJSON.JSONObject _json)
    {
        {
            _json["Id"] = new JSONNumber(Id);
        }
        {

            if (CSName == null) { throw new System.ArgumentNullException(); }
            _json["CSName"] = new JSONString(CSName);
        }
        {

            if (Desc == null) { throw new System.ArgumentNullException(); }
            _json["Desc"] = new JSONString(Desc);
        }
        {

            if (AssetName == null) { throw new System.ArgumentNullException(); }
            _json["AssetName"] = new JSONString(AssetName);
        }
        {

            if (EntityGroupName == null) { throw new System.ArgumentNullException(); }
            _json["EntityGroupName"] = new JSONString(EntityGroupName);
        }
        {
            _json["Priority"] = new JSONNumber(Priority);
        }
    }

    public static DREntity LoadJsonDREntity(SimpleJSON.JSONNode _json)
    {
        DREntity obj = new DREntity();
        obj.LoadJson((SimpleJSON.JSONObject)_json);
        return obj;
    }
        
    public static void SaveJsonDREntity(DREntity _obj, SimpleJSON.JSONNode _json)
    {
        _obj.SaveJson((SimpleJSON.JSONObject)_json);
    }

    /// <summary>
    /// 实体编号
    /// </summary>
    public int Id;

    /// <summary>
    /// 实体编号代码名（程序填）
    /// </summary>
    public string CSName;

    /// <summary>
    /// 策划备注
    /// </summary>
    public string Desc;

    /// <summary>
    /// 资源名称
    /// </summary>
    public string AssetName;

    /// <summary>
    /// 实体组名称
    /// </summary>
    public string EntityGroupName;

    /// <summary>
    /// 加载优先级
    /// </summary>
    public int Priority;

}

}

