
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using SimpleJSON;
using Luban;

namespace Game.Editor
{

public sealed class DRScene :  Luban.EditorBeanBase 
{
    public DRScene()
    {
            AssetName = "";
    }

    public override void LoadJson(SimpleJSON.JSONObject _json)
    {
        { 
            var _fieldJson = _json["Id"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  Id = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["AssetName"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  AssetName = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["BackgroundMusicId"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  BackgroundMusicId = _fieldJson;
            }
        }
        
    }

    public override void SaveJson(SimpleJSON.JSONObject _json)
    {
        {
            _json["Id"] = new JSONNumber(Id);
        }
        {

            if (AssetName == null) { throw new System.ArgumentNullException(); }
            _json["AssetName"] = new JSONString(AssetName);
        }
        {
            _json["BackgroundMusicId"] = new JSONNumber(BackgroundMusicId);
        }
    }

    public static DRScene LoadJsonDRScene(SimpleJSON.JSONNode _json)
    {
        DRScene obj = new DRScene();
        obj.LoadJson((SimpleJSON.JSONObject)_json);
        return obj;
    }
        
    public static void SaveJsonDRScene(DRScene _obj, SimpleJSON.JSONNode _json)
    {
        _obj.SaveJson((SimpleJSON.JSONObject)_json);
    }

    /// <summary>
    /// 场景编号
    /// </summary>
    public int Id;

    /// <summary>
    /// 资源名称
    /// </summary>
    public string AssetName;

    /// <summary>
    /// 背景音乐编号
    /// </summary>
    public int BackgroundMusicId;

}

}
