
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using SimpleJSON;
using Luban;

namespace Game.Editor
{

public sealed class DRSound :  Luban.EditorBeanBase 
{
    public DRSound()
    {
            CSName = "";
            Desc = "";
            AssetName = "";
            SoundGroupName = "";
    }

    public override void LoadJson(SimpleJSON.JSONObject _json)
    {
        { 
            var _fieldJson = _json["Id"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  Id = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["CSName"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  CSName = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["Desc"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  Desc = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["AssetName"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  AssetName = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["SoundGroupName"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  SoundGroupName = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["Priority"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  Priority = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["Loop"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsBoolean) { throw new SerializationException(); }  Loop = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["Volume"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  Volume = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["SpatialBlend"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  SpatialBlend = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["MaxDistance"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  MaxDistance = _fieldJson;
            }
        }
        
    }

    public override void SaveJson(SimpleJSON.JSONObject _json)
    {
        {
            _json["Id"] = new JSONNumber(Id);
        }
        {

            if (CSName == null) { throw new System.ArgumentNullException(); }
            _json["CSName"] = new JSONString(CSName);
        }
        {

            if (Desc == null) { throw new System.ArgumentNullException(); }
            _json["Desc"] = new JSONString(Desc);
        }
        {

            if (AssetName == null) { throw new System.ArgumentNullException(); }
            _json["AssetName"] = new JSONString(AssetName);
        }
        {

            if (SoundGroupName == null) { throw new System.ArgumentNullException(); }
            _json["SoundGroupName"] = new JSONString(SoundGroupName);
        }
        {
            _json["Priority"] = new JSONNumber(Priority);
        }
        {
            _json["Loop"] = new JSONBool(Loop);
        }
        {
            _json["Volume"] = new JSONNumber(Volume);
        }
        {
            _json["SpatialBlend"] = new JSONNumber(SpatialBlend);
        }
        {
            _json["MaxDistance"] = new JSONNumber(MaxDistance);
        }
    }

    public static DRSound LoadJsonDRSound(SimpleJSON.JSONNode _json)
    {
        DRSound obj = new DRSound();
        obj.LoadJson((SimpleJSON.JSONObject)_json);
        return obj;
    }
        
    public static void SaveJsonDRSound(DRSound _obj, SimpleJSON.JSONNode _json)
    {
        _obj.SaveJson((SimpleJSON.JSONObject)_json);
    }

    /// <summary>
    /// 声音编号
    /// </summary>
    public int Id;

    /// <summary>
    /// 代码名（程序填）
    /// </summary>
    public string CSName;

    /// <summary>
    /// 备注
    /// </summary>
    public string Desc;

    /// <summary>
    /// 资源名称
    /// </summary>
    public string AssetName;

    /// <summary>
    /// 声音组名称
    /// </summary>
    public string SoundGroupName;

    /// <summary>
    /// 优先级（默认0，128最高，-128最低）
    /// </summary>
    public int Priority;

    /// <summary>
    /// 是否循环
    /// </summary>
    public bool Loop;

    /// <summary>
    /// 音量（0~1）
    /// </summary>
    public float Volume;

    /// <summary>
    /// 声音空间混合量（0为2D，1为3D，中间值混合效果）
    /// </summary>
    public float SpatialBlend;

    /// <summary>
    /// 声音最大距离
    /// </summary>
    public float MaxDistance;

}

}

