// This is automatically generated by CodeBind. Please do not modify it.

namespace ET.Client
{
    public partial class MonoUILogin : ETMonoUGFUIForm
    {
        public CodeBind.CSCodeBindMono Mono { get; private set; }
        public UnityEngine.Transform Transform { get; private set; }

        public UnityEngine.UI.InputField AccountInputField { get; private set; }
        public UnityEngine.UI.InputField PasswordInputField { get; private set; }
        public UnityEngine.UI.Button LoginButton { get; private set; }
        public UnityEngine.Transform TestWidgetTransform { get; private set; }


        
    }
}
