// This is automatically generated by CodeBind. Please do not modify it.

namespace ET.Client
{
    [Sirenix.OdinInspector.InfoBox("BindData exist empty.", Sirenix.OdinInspector.InfoMessageType.Warning, VisibleIf = "CheckBindDataExitEmpty")]
    public partial class MonoUIFormLogin
    {
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.InputField m_AccountInputField;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.Button m_LoginButton;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.InputField m_PasswordInputField;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private ET.Client.MonoUIWidgetTest m_TestWidgetTest;


        public UnityEngine.UI.InputField AccountInputField => m_AccountInputField;
        public UnityEngine.UI.Button LoginButton => m_LoginButton;
        public UnityEngine.UI.InputField PasswordInputField => m_PasswordInputField;
        public ET.Client.MonoUIWidgetTest TestWidgetTest => m_TestWidgetTest;


        private bool CheckBindDataExitEmpty()
        {
            if (this.m_AccountInputField == null) return true;
            if (this.m_LoginButton == null) return true;
            if (this.m_PasswordInputField == null) return true;
            if (this.m_TestWidgetTest == null) return true;
            return false;
        }
    }
}
