//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Threading.Tasks;


namespace cfg
{
   
public partial class DataTables
{
    public DTDefaultConfig DTDefaultConfig {get; private set; }
    public ET.DTStartMachineConfig DTStartMachineConfig {get; private set; }
    public ET.DTStartProcessConfig DTStartProcessConfig {get; private set; }
    public ET.DTStartSceneConfig DTStartSceneConfig {get; private set; }
    public ET.DTStartZoneConfig DTStartZoneConfig {get; private set; }
    public ET.DTAIConfig DTAIConfig {get; private set; }
    public ET.DTUnitConfig DTUnitConfig {get; private set; }

    public void Load(System.Func<string, ByteBuf> loader)
    {
        var tables = new System.Collections.Generic.Dictionary<string, object>();
        DTDefaultConfig = new DTDefaultConfig(loader("dtdefaultconfig")); 
        tables.Add("DTDefaultConfig", DTDefaultConfig);
        DTStartMachineConfig = new ET.DTStartMachineConfig(loader("et_dtstartmachineconfig")); 
        tables.Add("ET.DTStartMachineConfig", DTStartMachineConfig);
        DTStartProcessConfig = new ET.DTStartProcessConfig(loader("et_dtstartprocessconfig")); 
        tables.Add("ET.DTStartProcessConfig", DTStartProcessConfig);
        DTStartSceneConfig = new ET.DTStartSceneConfig(loader("et_dtstartsceneconfig")); 
        tables.Add("ET.DTStartSceneConfig", DTStartSceneConfig);
        DTStartZoneConfig = new ET.DTStartZoneConfig(loader("et_dtstartzoneconfig")); 
        tables.Add("ET.DTStartZoneConfig", DTStartZoneConfig);
        DTAIConfig = new ET.DTAIConfig(loader("et_dtaiconfig")); 
        tables.Add("ET.DTAIConfig", DTAIConfig);
        DTUnitConfig = new ET.DTUnitConfig(loader("et_dtunitconfig")); 
        tables.Add("ET.DTUnitConfig", DTUnitConfig);

        PostInit();
        DTDefaultConfig.Resolve(tables); 
        DTStartMachineConfig.Resolve(tables); 
        DTStartProcessConfig.Resolve(tables); 
        DTStartSceneConfig.Resolve(tables); 
        DTStartZoneConfig.Resolve(tables); 
        DTAIConfig.Resolve(tables); 
        DTUnitConfig.Resolve(tables); 
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        DTDefaultConfig.TranslateText(translator); 
        DTStartMachineConfig.TranslateText(translator); 
        DTStartProcessConfig.TranslateText(translator); 
        DTStartSceneConfig.TranslateText(translator); 
        DTStartZoneConfig.TranslateText(translator); 
        DTAIConfig.TranslateText(translator); 
        DTUnitConfig.TranslateText(translator); 
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}