//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace cfg
{
public sealed partial class DRDefaultConfig :  Bright.Config.BeanBase 
{
    public DRDefaultConfig(ByteBuf _buf) 
    {
        MaxMatchTime = _buf.ReadLong();
        Test = _buf.ReadInt();
        PostInit();
    }

    public static DRDefaultConfig DeserializeDRDefaultConfig(ByteBuf _buf)
    {
        return new DRDefaultConfig(_buf);
    }

    /// <summary>
    /// 匹配最大时间
    /// </summary>
    public long MaxMatchTime { get; private set; }
    /// <summary>
    /// 匹配最大时间
    /// </summary>
    public int Test { get; private set; }

    public const int __ID__ = -2056859915;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "MaxMatchTime:" + MaxMatchTime + ","
        + "Test:" + Test + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}