//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace cfg.ET
{
   
public partial class DTStartSceneConfig
{
    private readonly List<ET.DRStartSceneConfig> _dataList;

    private Dictionary<(string, int), ET.DRStartSceneConfig> _dataMapUnion;

    public DTStartSceneConfig(ByteBuf _buf)
    {
        _dataList = new List<ET.DRStartSceneConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            ET.DRStartSceneConfig _v;
            _v = ET.DRStartSceneConfig.DeserializeDRStartSceneConfig(_buf);
            _dataList.Add(_v);
        }
        _dataMapUnion = new Dictionary<(string, int), ET.DRStartSceneConfig>();
        foreach(var _v in _dataList)
        {
            _dataMapUnion.Add((_v.StartConfig, _v.Id), _v);
        }
        PostInit();
    }


    public List<ET.DRStartSceneConfig> DataList => _dataList;

    public ET.DRStartSceneConfig Get(string StartConfig, int Id) => _dataMapUnion.TryGetValue((StartConfig, Id), out ET.DRStartSceneConfig __v) ? __v : null;

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}