//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace cfg.ET
{
   
public partial class DTUnitConfig
{
    private readonly Dictionary<int, ET.DRUnitConfig> _dataMap;
    private readonly List<ET.DRUnitConfig> _dataList;
    
    public DTUnitConfig(ByteBuf _buf)
    {
        _dataMap = new Dictionary<int, ET.DRUnitConfig>();
        _dataList = new List<ET.DRUnitConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            ET.DRUnitConfig _v;
            _v = ET.DRUnitConfig.DeserializeDRUnitConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<int, ET.DRUnitConfig> DataMap => _dataMap;
    public List<ET.DRUnitConfig> DataList => _dataList;

    public ET.DRUnitConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public ET.DRUnitConfig Get(int key) => _dataMap[key];
    public ET.DRUnitConfig this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}