
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using SimpleJSON;
using Luban;

namespace ET.Editor
{

public sealed class DROneConfig :  Luban.EditorBeanBase 
{
    public DROneConfig()
    {
    }

    public override void LoadJson(SimpleJSON.JSONObject _json)
    {
        { 
            var _fieldJson = _json["MaxMatchTime"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  MaxMatchTime = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["Test"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  Test = _fieldJson;
            }
        }
        
    }

    public override void SaveJson(SimpleJSON.JSONObject _json)
    {
        {
            _json["MaxMatchTime"] = new JSONNumber(MaxMatchTime);
        }
        {
            _json["Test"] = new JSONNumber(Test);
        }
    }

    public static DROneConfig LoadJsonDROneConfig(SimpleJSON.JSONNode _json)
    {
        DROneConfig obj = new DROneConfig();
        obj.LoadJson((SimpleJSON.JSONObject)_json);
        return obj;
    }
        
    public static void SaveJsonDROneConfig(DROneConfig _obj, SimpleJSON.JSONNode _json)
    {
        _obj.SaveJson((SimpleJSON.JSONObject)_json);
    }

    /// <summary>
    /// 匹配最大时间
    /// </summary>
    public long MaxMatchTime;

    /// <summary>
    /// 匹配最大时间
    /// </summary>
    public int Test;

}

}

