
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using SimpleJSON;
using Luban;

namespace ET.Editor
{

public sealed class DRStartProcessConfig :  Luban.EditorBeanBase 
{
    public DRStartProcessConfig()
    {
            StartConfig = "";
    }

    public override void LoadJson(SimpleJSON.JSONObject _json)
    {
        { 
            var _fieldJson = _json["StartConfig"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  StartConfig = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["Id"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  Id = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["MachineId"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  MachineId = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["Port"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  Port = _fieldJson;
            }
        }
        
    }

    public override void SaveJson(SimpleJSON.JSONObject _json)
    {
        {

            if (StartConfig == null) { throw new System.ArgumentNullException(); }
            _json["StartConfig"] = new JSONString(StartConfig);
        }
        {
            _json["Id"] = new JSONNumber(Id);
        }
        {
            _json["MachineId"] = new JSONNumber(MachineId);
        }
        {
            _json["Port"] = new JSONNumber(Port);
        }
    }

    public static DRStartProcessConfig LoadJsonDRStartProcessConfig(SimpleJSON.JSONNode _json)
    {
        DRStartProcessConfig obj = new DRStartProcessConfig();
        obj.LoadJson((SimpleJSON.JSONObject)_json);
        return obj;
    }
        
    public static void SaveJsonDRStartProcessConfig(DRStartProcessConfig _obj, SimpleJSON.JSONNode _json)
    {
        _obj.SaveJson((SimpleJSON.JSONObject)_json);
    }

    /// <summary>
    /// 开启类型
    /// </summary>
    public string StartConfig;

    /// <summary>
    /// Id
    /// </summary>
    public int Id;

    /// <summary>
    /// 所属机器
    /// </summary>
    public int MachineId;

    /// <summary>
    /// 外网端口
    /// </summary>
    public int Port;

}

}

