
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using SimpleJSON;
using Luban;

namespace ET.Editor
{

public sealed class DRStartMachineConfig :  Luban.EditorBeanBase 
{
    public DRStartMachineConfig()
    {
            StartConfig = "";
            InnerIP = "";
            OuterIP = "";
            WatcherPort = "";
    }

    public override void LoadJson(SimpleJSON.JSONObject _json)
    {
        { 
            var _fieldJson = _json["StartConfig"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  StartConfig = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["Id"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  Id = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["InnerIP"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  InnerIP = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["OuterIP"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  OuterIP = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["WatcherPort"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  WatcherPort = _fieldJson;
            }
        }
        
    }

    public override void SaveJson(SimpleJSON.JSONObject _json)
    {
        {

            if (StartConfig == null) { throw new System.ArgumentNullException(); }
            _json["StartConfig"] = new JSONString(StartConfig);
        }
        {
            _json["Id"] = new JSONNumber(Id);
        }
        {

            if (InnerIP == null) { throw new System.ArgumentNullException(); }
            _json["InnerIP"] = new JSONString(InnerIP);
        }
        {

            if (OuterIP == null) { throw new System.ArgumentNullException(); }
            _json["OuterIP"] = new JSONString(OuterIP);
        }
        {

            if (WatcherPort == null) { throw new System.ArgumentNullException(); }
            _json["WatcherPort"] = new JSONString(WatcherPort);
        }
    }

    public static DRStartMachineConfig LoadJsonDRStartMachineConfig(SimpleJSON.JSONNode _json)
    {
        DRStartMachineConfig obj = new DRStartMachineConfig();
        obj.LoadJson((SimpleJSON.JSONObject)_json);
        return obj;
    }
        
    public static void SaveJsonDRStartMachineConfig(DRStartMachineConfig _obj, SimpleJSON.JSONNode _json)
    {
        _obj.SaveJson((SimpleJSON.JSONObject)_json);
    }

    /// <summary>
    /// 开启类型
    /// </summary>
    public string StartConfig;

    /// <summary>
    /// Id
    /// </summary>
    public int Id;

    /// <summary>
    /// 内网地址
    /// </summary>
    public string InnerIP;

    /// <summary>
    /// 外网地址
    /// </summary>
    public string OuterIP;

    /// <summary>
    /// 守护进程端口
    /// </summary>
    public string WatcherPort;

}

}

