
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using SimpleJSON;
using Luban;

namespace ET.Editor
{

public sealed class DRStartSceneConfig :  Luban.EditorBeanBase 
{
    public DRStartSceneConfig()
    {
            StartConfig = "";
            SceneType = "";
            Name = "";
    }

    public override void LoadJson(SimpleJSON.JSONObject _json)
    {
        { 
            var _fieldJson = _json["StartConfig"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  StartConfig = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["Id"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  Id = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["Process"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  Process = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["Zone"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  Zone = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["SceneType"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  SceneType = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["Name"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  Name = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["Port"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  Port = _fieldJson;
            }
        }
        
    }

    public override void SaveJson(SimpleJSON.JSONObject _json)
    {
        {

            if (StartConfig == null) { throw new System.ArgumentNullException(); }
            _json["StartConfig"] = new JSONString(StartConfig);
        }
        {
            _json["Id"] = new JSONNumber(Id);
        }
        {
            _json["Process"] = new JSONNumber(Process);
        }
        {
            _json["Zone"] = new JSONNumber(Zone);
        }
        {

            if (SceneType == null) { throw new System.ArgumentNullException(); }
            _json["SceneType"] = new JSONString(SceneType);
        }
        {

            if (Name == null) { throw new System.ArgumentNullException(); }
            _json["Name"] = new JSONString(Name);
        }
        {
            _json["Port"] = new JSONNumber(Port);
        }
    }

    public static DRStartSceneConfig LoadJsonDRStartSceneConfig(SimpleJSON.JSONNode _json)
    {
        DRStartSceneConfig obj = new DRStartSceneConfig();
        obj.LoadJson((SimpleJSON.JSONObject)_json);
        return obj;
    }
        
    public static void SaveJsonDRStartSceneConfig(DRStartSceneConfig _obj, SimpleJSON.JSONNode _json)
    {
        _obj.SaveJson((SimpleJSON.JSONObject)_json);
    }

    /// <summary>
    /// 开启类型
    /// </summary>
    public string StartConfig;

    /// <summary>
    /// Id
    /// </summary>
    public int Id;

    /// <summary>
    /// 所属进程
    /// </summary>
    public int Process;

    /// <summary>
    /// 所属区
    /// </summary>
    public int Zone;

    /// <summary>
    /// 类型
    /// </summary>
    public string SceneType;

    /// <summary>
    /// 名字
    /// </summary>
    public string Name;

    /// <summary>
    /// 外网端口
    /// </summary>
    public int Port;

}

}

