// This is automatically generated by CodeBind. Please do not modify it.

namespace ET.Client
{
    public partial class MonoUIFormLSLogin
    {
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.InputField m_AccountInputField;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.Button m_LoginButton;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.InputField m_PasswordInputField;


        public UnityEngine.UI.InputField AccountInputField => m_AccountInputField;
        public UnityEngine.UI.Button LoginButton => m_LoginButton;
        public UnityEngine.UI.InputField PasswordInputField => m_PasswordInputField;


    }
}
