// This is automatically generated by CodeBind. Please do not modify it.

namespace ET.Client
{
    [EnableClass]
    public partial class ETMonoWidgetTest : ETMonoUGFUIWidget
    {
        public CodeBind.CSCodeBindMono Mono { get; private set; }
        public UnityEngine.Transform Transform { get; private set; }

        public UnityEngine.UI.UXText TestTextUXText { get; private set; }


        
    }
}
