// This is automatically generated by CodeBind. Please do not modify it.

namespace ET.Client
{
    public partial class ETMonoWidgetTest
    {
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.UXText m_TestTextUXText;


        public UnityEngine.UI.UXText TestTextUXText => m_TestTextUXText;


    }
}
