// This is automatically generated by CodeBind. Please do not modify it.

namespace ET.Client
{
    public partial class UGFUIWidgetTest : CodeBind.ICSCodeBind
    {
        public CodeBind.CSCodeBindMono Mono { get; private set; }
        public UnityEngine.Transform Transform { get; private set; }

        public UnityEngine.UI.UXText TestTextUXText { get; private set; }


        public void InitBind(CodeBind.CSCodeBindMono mono)
        {
            Mono = mono;
            Transform = mono.transform;
            TestTextUXText = Mono.BindComponents[0] as UnityEngine.UI.UXText;
        }

        public void ClearBind()
        {
            Mono = null;
            Transform = null;
            TestTextUXText = null;
        }
    }
}
