<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <Nullable>enable</Nullable>
    <LangVersion>12</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="3.9.0" PrivateAssets="all" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.9.0" />
    <PackageReference Include="NUnit" Version="4.0.1" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.5.0" />
    <PackageReference Include="XuToWei.ReactiveBinding" Version="1.2.2" ExcludeAssets="analyzers" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Share.SourceGenerator.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\..\..\Unity\Assets\Scripts\Library\ET\Core\Runtime\Analyzer\EnableClassAttribute.cs" Link="Runtime\EnableClassAttribute.cs" />
    <Compile Include="..\..\..\Unity\Assets\Scripts\Library\ET\Core\Runtime\World\Module\EventSystem\BaseAttribute.cs" Link="Runtime\BaseAttribute.cs" />
    <Compile Include="..\..\..\Unity\Assets\Scripts\Library\ET\Core\Runtime\Analyzer\EntitySystemOf.cs" Link="Runtime\EntitySystemOf.cs" />
    <Compile Include="..\..\..\Unity\Assets\Scripts\Game\ET\Code\Model\Share\Module\Reactive\ETReactiveAttributes.cs" Link="Runtime\ETReactiveAttributes.cs" />
    <Compile Include="..\..\..\Unity\Assets\Scripts\Game\ET\Code\Model\Share\Module\Reactive\ETReactiveSystem.cs" Link="Runtime\ETReactiveSystem.cs" />
  </ItemGroup>
</Project>
