//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace Game
{
public sealed partial class DRMusic :  Bright.Config.BeanBase 
{
    public DRMusic(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        AssetName = _buf.ReadString();
        Volume = _buf.ReadFloat();
        PostInit();
    }

    public static DRMusic DeserializeDRMusic(ByteBuf _buf)
    {
        return new DRMusic(_buf);
    }

    /// <summary>
    /// 音乐编号
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 资源名称
    /// </summary>
    public string AssetName { get; private set; }
    /// <summary>
    /// 音量（0~1）
    /// </summary>
    public float Volume { get; private set; }

    public const int __ID__ = -1651958217;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, IDataTable> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "AssetName:" + AssetName + ","
        + "Volume:" + Volume + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}