
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace Game
{
public sealed partial class DRSound : Luban.BeanBase
{
    public DRSound(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["AssetName"].IsString) { throw new SerializationException(); }  AssetName = _buf["AssetName"]; }
        { if(!_buf["SoundGroupName"].IsString) { throw new SerializationException(); }  SoundGroupName = _buf["SoundGroupName"]; }
        { if(!_buf["Priority"].IsNumber) { throw new SerializationException(); }  Priority = _buf["Priority"]; }
        { if(!_buf["Loop"].IsBoolean) { throw new SerializationException(); }  Loop = _buf["Loop"]; }
        { if(!_buf["Volume"].IsNumber) { throw new SerializationException(); }  Volume = _buf["Volume"]; }
        { if(!_buf["SpatialBlend"].IsNumber) { throw new SerializationException(); }  SpatialBlend = _buf["SpatialBlend"]; }
        { if(!_buf["MaxDistance"].IsNumber) { throw new SerializationException(); }  MaxDistance = _buf["MaxDistance"]; }
        PostInit();
    }

    public static DRSound DeserializeDRSound(JSONNode _buf)
    {
        return new DRSound(_buf);
    }

    /// <summary>
    /// 声音编号
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 资源名称
    /// </summary>
    public readonly string AssetName;
    /// <summary>
    /// 声音组名称
    /// </summary>
    public readonly string SoundGroupName;
    /// <summary>
    /// 优先级（默认0，128最高，-128最低）
    /// </summary>
    public readonly int Priority;
    /// <summary>
    /// 是否循环
    /// </summary>
    public readonly bool Loop;
    /// <summary>
    /// 音量（0~1）
    /// </summary>
    public readonly float Volume;
    /// <summary>
    /// 声音空间混合量（0为2D，1为3D，中间值混合效果）
    /// </summary>
    public readonly float SpatialBlend;
    /// <summary>
    /// 声音最大距离
    /// </summary>
    public readonly float MaxDistance;
    public const int __ID__ = -1646593759;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(TablesComponent tables)
    {
        
        
        
        
        
        
        
        
        PostResolve();
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "AssetName:" + AssetName + ","
        + "SoundGroupName:" + SoundGroupName + ","
        + "Priority:" + Priority + ","
        + "Loop:" + Loop + ","
        + "Volume:" + Volume + ","
        + "SpatialBlend:" + SpatialBlend + ","
        + "MaxDistance:" + MaxDistance + ","
        + "}";
    }

    partial void PostInit();
    partial void PostResolve();
}
}
