
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace Game
{
public sealed partial class DRUIForm : Luban.BeanBase
{
    public DRUIForm(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["AssetName"].IsString) { throw new SerializationException(); }  AssetName = _buf["AssetName"]; }
        { if(!_buf["UIGroupName"].IsString) { throw new SerializationException(); }  UIGroupName = _buf["UIGroupName"]; }
        { if(!_buf["AllowMultiInstance"].IsBoolean) { throw new SerializationException(); }  AllowMultiInstance = _buf["AllowMultiInstance"]; }
        { if(!_buf["PauseCoveredUIForm"].IsBoolean) { throw new SerializationException(); }  PauseCoveredUIForm = _buf["PauseCoveredUIForm"]; }
        PostInit();
    }

    public static DRUIForm DeserializeDRUIForm(JSONNode _buf)
    {
        return new DRUIForm(_buf);
    }

    /// <summary>
    /// 界面编号
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 资源名称
    /// </summary>
    public readonly string AssetName;
    /// <summary>
    /// 界面组名称
    /// </summary>
    public readonly string UIGroupName;
    /// <summary>
    /// 是否允许多个界面实例
    /// </summary>
    public readonly bool AllowMultiInstance;
    /// <summary>
    /// 是否暂停被其覆盖的界面
    /// </summary>
    public readonly bool PauseCoveredUIForm;
    public const int __ID__ = 515966854;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(TablesComponent tables)
    {
        
        
        
        
        
        PostResolve();
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "AssetName:" + AssetName + ","
        + "UIGroupName:" + UIGroupName + ","
        + "AllowMultiInstance:" + AllowMultiInstance + ","
        + "PauseCoveredUIForm:" + PauseCoveredUIForm + ","
        + "}";
    }

    partial void PostInit();
    partial void PostResolve();
}
}
