
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace Game
{
public sealed partial class DRUISound : Luban.BeanBase
{
    public DRUISound(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["AssetName"].IsString) { throw new SerializationException(); }  AssetName = _buf["AssetName"]; }
        { if(!_buf["Priority"].IsNumber) { throw new SerializationException(); }  Priority = _buf["Priority"]; }
        { if(!_buf["Volume"].IsNumber) { throw new SerializationException(); }  Volume = _buf["Volume"]; }
        PostInit();
    }

    public static DRUISound DeserializeDRUISound(JSONNode _buf)
    {
        return new DRUISound(_buf);
    }

    /// <summary>
    /// 声音编号
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 资源名称
    /// </summary>
    public readonly string AssetName;
    /// <summary>
    /// 优先级（默认0，128最高，-128最低）
    /// </summary>
    public readonly int Priority;
    /// <summary>
    /// 音量（0~1）
    /// </summary>
    public readonly float Volume;
    public const int __ID__ = -1172887923;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(TablesComponent tables)
    {
        
        
        
        
        PostResolve();
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "AssetName:" + AssetName + ","
        + "Priority:" + Priority + ","
        + "Volume:" + Volume + ","
        + "}";
    }

    partial void PostInit();
    partial void PostResolve();
}
}
