//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace Game
{

public partial class Tables
{
    public DTUIForm DTUIForm { private set; get; }
    public DTEntity DTEntity { private set; get; }
    public DTScene DTScene { private set; get; }
    public DTSound DTSound { private set; get; }
    public DTUISound DTUISound { private set; get; }
    public DTMusic DTMusic { private set; get; }
    public DTOneConfig DTOneConfig { private set; get; }

    private Dictionary<string, IDataTable> _tables;

    public IEnumerable<IDataTable> DataTables => _tables.Values;

    public IDataTable GetDataTable(string tableName) => _tables.TryGetValue(tableName, out var v) ? v : null;

    public async Task LoadAsync(System.Func<string, Task<ByteBuf>> loader)
    {
        _tables = new Dictionary<string, IDataTable>();
        List<Task> loadTasks = new List<Task>();
        DTUIForm = new DTUIForm(() => loader("dtuiform")); 
        loadTasks.Add(DTUIForm.LoadAsync());
        _tables.Add("DTUIForm", DTUIForm);
        DTEntity = new DTEntity(() => loader("dtentity")); 
        loadTasks.Add(DTEntity.LoadAsync());
        _tables.Add("DTEntity", DTEntity);
        DTScene = new DTScene(() => loader("dtscene")); 
        loadTasks.Add(DTScene.LoadAsync());
        _tables.Add("DTScene", DTScene);
        DTSound = new DTSound(() => loader("dtsound")); 
        loadTasks.Add(DTSound.LoadAsync());
        _tables.Add("DTSound", DTSound);
        DTUISound = new DTUISound(() => loader("dtuisound")); 
        loadTasks.Add(DTUISound.LoadAsync());
        _tables.Add("DTUISound", DTUISound);
        DTMusic = new DTMusic(() => loader("dtmusic")); 
        loadTasks.Add(DTMusic.LoadAsync());
        _tables.Add("DTMusic", DTMusic);
        DTOneConfig = new DTOneConfig(() => loader("dtoneconfig")); 
        loadTasks.Add(DTOneConfig.LoadAsync());
        _tables.Add("DTOneConfig", DTOneConfig);

        await Task.WhenAll(loadTasks);

        PostInit();
        DTUIForm.Resolve(_tables); 
        DTEntity.Resolve(_tables); 
        DTScene.Resolve(_tables); 
        DTSound.Resolve(_tables); 
        DTUISound.Resolve(_tables); 
        DTMusic.Resolve(_tables); 
        DTOneConfig.Resolve(_tables); 
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        DTUIForm.TranslateText(translator); 
        DTEntity.TranslateText(translator); 
        DTScene.TranslateText(translator); 
        DTSound.TranslateText(translator); 
        DTUISound.TranslateText(translator); 
        DTMusic.TranslateText(translator); 
        DTOneConfig.TranslateText(translator); 
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}