//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace ET
{
   
public sealed partial class DTRemoteBuilderConfig : IDataTable
{

    private DRRemoteBuilderConfig _data;

    private readonly System.Func<Task<ByteBuf>> _loadFunc;

    public DTRemoteBuilderConfig(System.Func<Task<ByteBuf>> loadFunc)
    {
        _loadFunc = loadFunc;
    }

    public async Task LoadAsync()
    {
        ByteBuf _buf = await _loadFunc();
        int n = _buf.ReadSize();
        if (n != 1) throw new SerializationException("table mode=one, but size != 1");
        _data = DRRemoteBuilderConfig.DeserializeDRRemoteBuilderConfig(_buf);
        PostInit();
    }


     public int Client => _data.Client;
     public string ServerIP => _data.ServerIP;
     public string ServerInnerIP => _data.ServerInnerIP;
     public string ServerOuterPort => _data.ServerOuterPort;
     public string ServerUnityPath => _data.ServerUnityPath;

    public void Resolve(Dictionary<string, IDataTable> _tables)
    {
        _data.Resolve(_tables);
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        _data.TranslateText(translator);
    }

    
    partial void PostInit();
    partial void PostResolve();
}

}