//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET
{
public sealed partial class RemoteBuilderData :  Bright.Config.BeanBase 
{
    public RemoteBuilderData(ByteBuf _buf) 
    {
        Client = _buf.ReadInt();
        ServerIP = _buf.ReadString();
        ServerInnerIP = _buf.ReadString();
        ServerPort = _buf.ReadString();
        ServerUnityPath = _buf.ReadString();
        PostInit();
    }

    public static RemoteBuilderData DeserializeRemoteBuilderData(ByteBuf _buf)
    {
        return new RemoteBuilderData(_buf);
    }

    public int Client { get; private set; }
    public string ServerIP { get; private set; }
    public string ServerInnerIP { get; private set; }
    public string ServerPort { get; private set; }
    public string ServerUnityPath { get; private set; }

    public const int __ID__ = 726152607;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, IDataTable> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Client:" + Client + ","
        + "ServerIP:" + ServerIP + ","
        + "ServerInnerIP:" + ServerInnerIP + ","
        + "ServerPort:" + ServerPort + ","
        + "ServerUnityPath:" + ServerUnityPath + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}