//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Threading.Tasks;



namespace Game.Hot
{ 
public partial class Tables
{
    public DTOneConfig DTOneConfig { private set; get; }

    private System.Collections.Generic.Dictionary<string, IDataTable> _tables;

    public System.Collections.Generic.IEnumerable<IDataTable> DataTables => _tables.Values;

    public IDataTable GetDataTable(string tableName) => _tables.TryGetValue(tableName, out var v) ? v : null;

    public async Task LoadAsync(System.Func<string, Task<ByteBuf>> loader)
    {
        _tables = new System.Collections.Generic.Dictionary<string, IDataTable>();
        DTOneConfig = new DTOneConfig(() => loader("dtoneconfig")); 
        await DTOneConfig.LoadAsync();
        _tables.Add("DTOneConfig", DTOneConfig);

        PostInit();
        DTOneConfig.Resolve(_tables); 
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        DTOneConfig.TranslateText(translator); 
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}