//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace Game.Hot
{
public sealed partial class DRArmor :  Bright.Config.BeanBase 
{
    public DRArmor(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        MaxHP = _buf.ReadInt();
        Defense = _buf.ReadInt();
        PostInit();
    }

    public static DRArmor DeserializeDRArmor(ByteBuf _buf)
    {
        return new DRArmor(_buf);
    }

    /// <summary>
    /// 装甲编号
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 最大生命
    /// </summary>
    public int MaxHP { get; private set; }
    /// <summary>
    /// 防御力
    /// </summary>
    public int Defense { get; private set; }

    public const int __ID__ = -1663135407;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, IDataTable> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "MaxHP:" + MaxHP + ","
        + "Defense:" + Defense + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}