//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;

namespace Game.Hot
{
public sealed partial class DROneConfig :  Bright.Config.BeanBase 
{
    public DROneConfig(ByteBuf _buf) 
    {
        GameId = _buf.ReadString();
        SceneMenu = _buf.ReadInt();
        SceneMain = _buf.ReadInt();
        PostInit();
    }

    public static DROneConfig DeserializeDROneConfig(ByteBuf _buf)
    {
        return new DROneConfig(_buf);
    }

    public string GameId { get; private set; }
    public int SceneMenu { get; private set; }
    public int SceneMain { get; private set; }
    public const int __ID__ = -2019618726;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, IDataTable> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "GameId:" + GameId + ","
        + "SceneMenu:" + SceneMenu + ","
        + "SceneMain:" + SceneMain + ","
        + "}";
    }

    partial void PostInit();
    partial void PostResolve();
}
}