//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;

namespace Game.Hot
{
public sealed partial class DRThruster :  Bright.Config.BeanBase 
{
    public DRThruster(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Speed = _buf.ReadFloat();
        PostInit();
    }

    public static DRThruster DeserializeDRThruster(ByteBuf _buf)
    {
        return new DRThruster(_buf);
    }

    /// <summary>
    /// 推进器编号
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 速度
    /// </summary>
    public float Speed { get; private set; }
    public const int __ID__ = -1106796109;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, IDataTable> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Speed:" + Speed + ","
        + "}";
    }

    partial void PostInit();
    partial void PostResolve();
}
}