
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace Game.Hot
{
public sealed partial class DRWeapon : Luban.BeanBase
{
    public DRWeapon(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Attack = _buf.ReadInt();
        AttackInterval = _buf.ReadFloat();
        BulletId = _buf.ReadInt();
        BulletSpeed = _buf.ReadFloat();
        BulletSoundId = _buf.ReadInt();
        PostInit();
    }

    public static DRWeapon DeserializeDRWeapon(ByteBuf _buf)
    {
        return new DRWeapon(_buf);
    }

    /// <summary>
    /// 武器编号
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 攻击力
    /// </summary>
    public readonly int Attack;
    /// <summary>
    /// 攻击间隔
    /// </summary>
    public readonly float AttackInterval;
    /// <summary>
    /// 子弹编号
    /// </summary>
    public readonly int BulletId;
    /// <summary>
    /// 子弹速度
    /// </summary>
    public readonly float BulletSpeed;
    /// <summary>
    /// 子弹声音编号
    /// </summary>
    public readonly int BulletSoundId;
    public const int __ID__ = 599888970;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
        PostResolveRef();
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Attack:" + Attack + ","
        + "AttackInterval:" + AttackInterval + ","
        + "BulletId:" + BulletId + ","
        + "BulletSpeed:" + BulletSpeed + ","
        + "BulletSoundId:" + BulletSoundId + ","
        + "}";
    }

    partial void PostInit();
    partial void PostResolveRef();
}
}
