//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace Game.Hot
{
public sealed partial class DRWeapon :  Bright.Config.BeanBase 
{
    public DRWeapon(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Attack = _buf.ReadInt();
        AttackInterval = _buf.ReadFloat();
        BulletId = _buf.ReadInt();
        BulletSpeed = _buf.ReadFloat();
        BulletSoundId = _buf.ReadInt();
        PostInit();
    }

    public static DRWeapon DeserializeDRWeapon(ByteBuf _buf)
    {
        return new DRWeapon(_buf);
    }

    /// <summary>
    /// 武器编号
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 攻击力
    /// </summary>
    public int Attack { get; private set; }
    /// <summary>
    /// 攻击间隔
    /// </summary>
    public float AttackInterval { get; private set; }
    /// <summary>
    /// 子弹编号
    /// </summary>
    public int BulletId { get; private set; }
    /// <summary>
    /// 子弹速度
    /// </summary>
    public float BulletSpeed { get; private set; }
    /// <summary>
    /// 子弹声音编号
    /// </summary>
    public int BulletSoundId { get; private set; }

    public const int __ID__ = 599888970;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, IDataTable> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Attack:" + Attack + ","
        + "AttackInterval:" + AttackInterval + ","
        + "BulletId:" + BulletId + ","
        + "BulletSpeed:" + BulletSpeed + ","
        + "BulletSoundId:" + BulletSoundId + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}