
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace Game.Hot
{
public partial class DTAircraft : IDataTable
{
    private readonly System.Collections.Generic.Dictionary<int, DRAircraft> _dataMap;
    private readonly System.Collections.Generic.List<DRAircraft> _dataList;
    private readonly System.Func<Cysharp.Threading.Tasks.UniTask<JSONNode>> _loadFunc;

    public DTAircraft(System.Func<Cysharp.Threading.Tasks.UniTask<JSONNode>> loadFunc)
    {
        _loadFunc = loadFunc;
        _dataMap = new System.Collections.Generic.Dictionary<int, DRAircraft>();
        _dataList = new System.Collections.Generic.List<DRAircraft>();
    }

    public async Cysharp.Threading.Tasks.UniTask LoadAsync()
    {
        JSONNode _json = await _loadFunc();
        _dataMap.Clear();
        _dataList.Clear();
        foreach(JSONNode _ele in _json.Children)
        {
            DRAircraft _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = DRAircraft.DeserializeDRAircraft(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public System.Collections.Generic.Dictionary<int, DRAircraft> DataMap => _dataMap;
    public System.Collections.Generic.List<DRAircraft> DataList => _dataList;
    public DRAircraft GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public DRAircraft Get(int key) => _dataMap[key];
    public DRAircraft this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
        PostResolve();
    }


    partial void PostInit();
    partial void PostResolve();
}
}

