
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using SimpleJSON;
using Luban;

namespace Game.Hot.Editor
{

public sealed class DRAircraft :  Luban.EditorBeanBase 
{
    public DRAircraft()
    {
            WeaponIds = new System.Collections.Generic.List<int>();
            ArmorIds = new System.Collections.Generic.List<int>();
    }

    public override void LoadJson(SimpleJSON.JSONObject _json)
    {
        { 
            var _fieldJson = _json["Id"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  Id = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["ThrusterId"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  ThrusterId = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["WeaponIds"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsArray) { throw new SerializationException(); } WeaponIds = new System.Collections.Generic.List<int>(); foreach(JSONNode __e in _fieldJson.Children) { int __v;  if(!__e.IsNumber) { throw new SerializationException(); }  __v = __e;  WeaponIds.Add(__v); }  
            }
        }
        
        { 
            var _fieldJson = _json["ArmorIds"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsArray) { throw new SerializationException(); } ArmorIds = new System.Collections.Generic.List<int>(); foreach(JSONNode __e in _fieldJson.Children) { int __v;  if(!__e.IsNumber) { throw new SerializationException(); }  __v = __e;  ArmorIds.Add(__v); }  
            }
        }
        
        { 
            var _fieldJson = _json["DeadEffectId"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  DeadEffectId = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["DeadSoundId"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  DeadSoundId = _fieldJson;
            }
        }
        
    }

    public override void SaveJson(SimpleJSON.JSONObject _json)
    {
        {
            _json["Id"] = new JSONNumber(Id);
        }
        {
            _json["ThrusterId"] = new JSONNumber(ThrusterId);
        }
        {

            if (WeaponIds == null) { throw new System.ArgumentNullException(); }
            { var __cjson = new JSONArray(); foreach(var _e in WeaponIds) { __cjson["null"] = new JSONNumber(_e); } _json["WeaponIds"] = __cjson; }
        }
        {

            if (ArmorIds == null) { throw new System.ArgumentNullException(); }
            { var __cjson = new JSONArray(); foreach(var _e in ArmorIds) { __cjson["null"] = new JSONNumber(_e); } _json["ArmorIds"] = __cjson; }
        }
        {
            _json["DeadEffectId"] = new JSONNumber(DeadEffectId);
        }
        {
            _json["DeadSoundId"] = new JSONNumber(DeadSoundId);
        }
    }

    public static DRAircraft LoadJsonDRAircraft(SimpleJSON.JSONNode _json)
    {
        DRAircraft obj = new DRAircraft();
        obj.LoadJson((SimpleJSON.JSONObject)_json);
        return obj;
    }
        
    public static void SaveJsonDRAircraft(DRAircraft _obj, SimpleJSON.JSONNode _json)
    {
        _obj.SaveJson((SimpleJSON.JSONObject)_json);
    }

    /// <summary>
    /// 战机编号
    /// </summary>
    public int Id;

    /// <summary>
    /// 推进器编号
    /// </summary>
    public int ThrusterId;

    /// <summary>
    /// 武器编号0
    /// </summary>
    public System.Collections.Generic.List<int> WeaponIds;

    /// <summary>
    /// 装甲编号0
    /// </summary>
    public System.Collections.Generic.List<int> ArmorIds;

    /// <summary>
    /// 死亡特效编号
    /// </summary>
    public int DeadEffectId;

    /// <summary>
    /// 死亡声音编号
    /// </summary>
    public int DeadSoundId;

}

}
