
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Luban.SimpleJSON;
using Luban;

namespace Game.Hot.Editor
{

public sealed class DRArmor :  Luban.EditorBeanBase 
{
    public DRArmor()
    {
    }

    public override void LoadJson(JSONObject _json)
    {
        { 
            var _fieldJson = _json["Id"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  Id = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["MaxHP"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  MaxHP = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["Defense"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  Defense = _fieldJson;
            }
        }
        
    }

    public override void SaveJson(JSONObject _json)
    {
        {
            _json["Id"] = new JSONNumber(Id);
        }
        {
            _json["MaxHP"] = new JSONNumber(MaxHP);
        }
        {
            _json["Defense"] = new JSONNumber(Defense);
        }
    }

    public static DRArmor LoadJsonDRArmor(JSONNode _json)
    {
        DRArmor obj = new DRArmor();
        obj.LoadJson((JSONObject)_json);
        return obj;
    }
        
    public static void SaveJsonDRArmor(DRArmor _obj, JSONNode _json)
    {
        _obj.SaveJson((JSONObject)_json);
    }

    /// <summary>
    /// 装甲编号
    /// </summary>
    public int Id;

    /// <summary>
    /// 最大生命
    /// </summary>
    public int MaxHP;

    /// <summary>
    /// 防御力
    /// </summary>
    public int Defense;

}
}

