
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using SimpleJSON;
using Luban;

namespace Game.Hot.Editor
{

public sealed class DRWeapon :  Luban.EditorBeanBase 
{
    public DRWeapon()
    {
    }

    public override void LoadJson(SimpleJSON.JSONObject _json)
    {
        { 
            var _fieldJson = _json["Id"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  Id = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["Attack"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  Attack = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["AttackInterval"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  AttackInterval = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["BulletId"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  BulletId = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["BulletSpeed"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  BulletSpeed = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["BulletSoundId"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  BulletSoundId = _fieldJson;
            }
        }
        
    }

    public override void SaveJson(SimpleJSON.JSONObject _json)
    {
        {
            _json["Id"] = new JSONNumber(Id);
        }
        {
            _json["Attack"] = new JSONNumber(Attack);
        }
        {
            _json["AttackInterval"] = new JSONNumber(AttackInterval);
        }
        {
            _json["BulletId"] = new JSONNumber(BulletId);
        }
        {
            _json["BulletSpeed"] = new JSONNumber(BulletSpeed);
        }
        {
            _json["BulletSoundId"] = new JSONNumber(BulletSoundId);
        }
    }

    public static DRWeapon LoadJsonDRWeapon(SimpleJSON.JSONNode _json)
    {
        DRWeapon obj = new DRWeapon();
        obj.LoadJson((SimpleJSON.JSONObject)_json);
        return obj;
    }
        
    public static void SaveJsonDRWeapon(DRWeapon _obj, SimpleJSON.JSONNode _json)
    {
        _obj.SaveJson((SimpleJSON.JSONObject)_json);
    }

    /// <summary>
    /// 武器编号
    /// </summary>
    public int Id;

    /// <summary>
    /// 攻击力
    /// </summary>
    public int Attack;

    /// <summary>
    /// 攻击间隔
    /// </summary>
    public float AttackInterval;

    /// <summary>
    /// 子弹编号
    /// </summary>
    public int BulletId;

    /// <summary>
    /// 子弹速度
    /// </summary>
    public float BulletSpeed;

    /// <summary>
    /// 子弹声音编号
    /// </summary>
    public int BulletSoundId;

}

}
