// This is automatically generated by CodeBind. Please do not modify it.

namespace ET.Client
{
    public partial class MonoUIFormLSLobby
    {
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.Button m_EnterMapButton;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.Button m_ReplayButton;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.InputField m_ReplayPathInputField;

        public UnityEngine.UI.Button EnterMapButton => this.m_EnterMapButton;
        public UnityEngine.UI.Button ReplayButton => this.m_ReplayButton;
        public UnityEngine.UI.InputField ReplayPathInputField => this.m_ReplayPathInputField;

#if UNITY_EDITOR
        [Sirenix.OdinInspector.OnInspectorGUI, Sirenix.OdinInspector.PropertyOrder(-99999), Sirenix.OdinInspector.ShowIf(nameof(CheckBindDataExitEmpty))]
        private void DrawBindDataExitEmptyWarning()
        {
            Sirenix.Utilities.Editor.SirenixEditorGUI.MessageBox("BindData contains empty reference.", UnityEditor.MessageType.Warning);
        }

        private bool CheckBindDataExitEmpty()
        {
            if (this.m_EnterMapButton == null) return true;
            if (this.m_ReplayButton == null) return true;
            if (this.m_ReplayPathInputField == null) return true;
            return false;
        }
#endif

    }
}
