//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET.Editor.item
{
    public enum EQuality
    {
        /// <summary>
        /// 最差品质
        /// </summary>
        WHITE = 1,
        /// <summary>
        /// 蓝色的
        /// </summary>
        BLUE = 2,
        /// <summary>
        /// 紫色的
        /// </summary>
        PURPLE = 3,
        /// <summary>
        /// 最高品质
        /// </summary>
        RED = 4,
    }

    public static partial class EQuality_Metadata
    {
        public static readonly Bright.Config.EditorEnumItemInfo WHITE = new Bright.Config.EditorEnumItemInfo("WHITE", "白", 1, "最差品质");
        public static readonly Bright.Config.EditorEnumItemInfo BLUE = new Bright.Config.EditorEnumItemInfo("BLUE", "蓝", 2, "蓝色的");
        public static readonly Bright.Config.EditorEnumItemInfo PURPLE = new Bright.Config.EditorEnumItemInfo("PURPLE", "紫", 3, "紫色的");
        public static readonly Bright.Config.EditorEnumItemInfo RED = new Bright.Config.EditorEnumItemInfo("RED", "红", 4, "最高品质");

        private static readonly System.Collections.Generic.List<Bright.Config.EditorEnumItemInfo> __items = new System.Collections.Generic.List<Bright.Config.EditorEnumItemInfo>
        {
            WHITE,
            BLUE,
            PURPLE,
            RED,
        };

        public static System.Collections.Generic.List<Bright.Config.EditorEnumItemInfo> GetItems() => __items;

        public static Bright.Config.EditorEnumItemInfo GetByName(string name)
        {
            return __items.Find(c => c.Name == name);
        }

        public static Bright.Config.EditorEnumItemInfo GetByNameOrAlias(string name)
        {
            return __items.Find(c => c.Name == name || c.Alias == name);
        }

        public static Bright.Config.EditorEnumItemInfo GetByValue(int value)
        {
            return __items.Find(c => c.Value == value);
        }
    }

}
