// This is automatically generated by CodeBind. Please do not modify it.

namespace ET.Client
{
    public partial class MonoUIFormSurvivorSkillChoice
    {
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("Binding Targets"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.Button m_Choice1Button;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("Binding Targets"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.GameObject m_Choice1GameObject;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("Binding Targets"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.Image m_Choice1Image;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("Binding Targets"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.RectTransform m_Choice1RectTransform;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("Binding Targets"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.GameObject m_Choice1LabelGameObject;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("Binding Targets"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.RectTransform m_Choice1LabelRectTransform;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("Binding Targets"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.Text m_Choice1LabelText;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("Binding Targets"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.Button m_Choice2Button;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("Binding Targets"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.GameObject m_Choice2GameObject;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("Binding Targets"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.Image m_Choice2Image;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("Binding Targets"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.RectTransform m_Choice2RectTransform;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("Binding Targets"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.GameObject m_Choice2LabelGameObject;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("Binding Targets"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.RectTransform m_Choice2LabelRectTransform;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("Binding Targets"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.Text m_Choice2LabelText;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("Binding Targets"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.Button m_Choice3Button;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("Binding Targets"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.GameObject m_Choice3GameObject;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("Binding Targets"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.Image m_Choice3Image;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("Binding Targets"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.RectTransform m_Choice3RectTransform;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("Binding Targets"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.GameObject m_Choice3LabelGameObject;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("Binding Targets"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.RectTransform m_Choice3LabelRectTransform;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("Binding Targets"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.Text m_Choice3LabelText;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("Binding Targets"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.GameObject m_StatusGameObject;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("Binding Targets"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.RectTransform m_StatusRectTransform;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("Binding Targets"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.UXText m_StatusUXText;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("Binding Targets"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.GameObject m_TitleGameObject;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("Binding Targets"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.RectTransform m_TitleRectTransform;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("Binding Targets"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.UXText m_TitleUXText;

        public UnityEngine.UI.Button Choice1Button => this.m_Choice1Button;
        public UnityEngine.GameObject Choice1GameObject => this.m_Choice1GameObject;
        public UnityEngine.UI.Image Choice1Image => this.m_Choice1Image;
        public UnityEngine.RectTransform Choice1RectTransform => this.m_Choice1RectTransform;
        public UnityEngine.GameObject Choice1LabelGameObject => this.m_Choice1LabelGameObject;
        public UnityEngine.RectTransform Choice1LabelRectTransform => this.m_Choice1LabelRectTransform;
        public UnityEngine.UI.Text Choice1LabelText => this.m_Choice1LabelText;
        public UnityEngine.UI.Button Choice2Button => this.m_Choice2Button;
        public UnityEngine.GameObject Choice2GameObject => this.m_Choice2GameObject;
        public UnityEngine.UI.Image Choice2Image => this.m_Choice2Image;
        public UnityEngine.RectTransform Choice2RectTransform => this.m_Choice2RectTransform;
        public UnityEngine.GameObject Choice2LabelGameObject => this.m_Choice2LabelGameObject;
        public UnityEngine.RectTransform Choice2LabelRectTransform => this.m_Choice2LabelRectTransform;
        public UnityEngine.UI.Text Choice2LabelText => this.m_Choice2LabelText;
        public UnityEngine.UI.Button Choice3Button => this.m_Choice3Button;
        public UnityEngine.GameObject Choice3GameObject => this.m_Choice3GameObject;
        public UnityEngine.UI.Image Choice3Image => this.m_Choice3Image;
        public UnityEngine.RectTransform Choice3RectTransform => this.m_Choice3RectTransform;
        public UnityEngine.GameObject Choice3LabelGameObject => this.m_Choice3LabelGameObject;
        public UnityEngine.RectTransform Choice3LabelRectTransform => this.m_Choice3LabelRectTransform;
        public UnityEngine.UI.Text Choice3LabelText => this.m_Choice3LabelText;
        public UnityEngine.GameObject StatusGameObject => this.m_StatusGameObject;
        public UnityEngine.RectTransform StatusRectTransform => this.m_StatusRectTransform;
        public UnityEngine.UI.UXText StatusUXText => this.m_StatusUXText;
        public UnityEngine.GameObject TitleGameObject => this.m_TitleGameObject;
        public UnityEngine.RectTransform TitleRectTransform => this.m_TitleRectTransform;
        public UnityEngine.UI.UXText TitleUXText => this.m_TitleUXText;

#if UNITY_EDITOR
        [Sirenix.OdinInspector.OnInspectorGUI, Sirenix.OdinInspector.PropertyOrder(-99999), Sirenix.OdinInspector.ShowIf(nameof(HasMissingTargets))]
        private void DrawMissingTargetsWarning()
        {
            Sirenix.Utilities.Editor.SirenixEditorGUI.MessageBox("Binding targets contain missing references.", UnityEditor.MessageType.Warning);
        }

        private bool HasMissingTargets()
        {
            if (this.m_Choice1Button == null) return true;
            if (this.m_Choice1GameObject == null) return true;
            if (this.m_Choice1Image == null) return true;
            if (this.m_Choice1RectTransform == null) return true;
            if (this.m_Choice1LabelGameObject == null) return true;
            if (this.m_Choice1LabelRectTransform == null) return true;
            if (this.m_Choice1LabelText == null) return true;
            if (this.m_Choice2Button == null) return true;
            if (this.m_Choice2GameObject == null) return true;
            if (this.m_Choice2Image == null) return true;
            if (this.m_Choice2RectTransform == null) return true;
            if (this.m_Choice2LabelGameObject == null) return true;
            if (this.m_Choice2LabelRectTransform == null) return true;
            if (this.m_Choice2LabelText == null) return true;
            if (this.m_Choice3Button == null) return true;
            if (this.m_Choice3GameObject == null) return true;
            if (this.m_Choice3Image == null) return true;
            if (this.m_Choice3RectTransform == null) return true;
            if (this.m_Choice3LabelGameObject == null) return true;
            if (this.m_Choice3LabelRectTransform == null) return true;
            if (this.m_Choice3LabelText == null) return true;
            if (this.m_StatusGameObject == null) return true;
            if (this.m_StatusRectTransform == null) return true;
            if (this.m_StatusUXText == null) return true;
            if (this.m_TitleGameObject == null) return true;
            if (this.m_TitleRectTransform == null) return true;
            if (this.m_TitleUXText == null) return true;
            return false;
        }
#endif

    }
}
