// This is automatically generated by CodeBind. Please do not modify it.

namespace ET.Client
{
    public partial class MonoUIFormSurvivorGameOver
    {
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("Binding Targets"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.Button m_ReturnToRoomButton;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("Binding Targets"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.GameObject m_ReturnToRoomGameObject;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("Binding Targets"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.RectTransform m_ReturnToRoomRectTransform;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("Binding Targets"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.GameObject m_StatusGameObject;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("Binding Targets"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.RectTransform m_StatusRectTransform;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("Binding Targets"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.UXText m_StatusUXText;

        public UnityEngine.UI.Button ReturnToRoomButton => this.m_ReturnToRoomButton;
        public UnityEngine.GameObject ReturnToRoomGameObject => this.m_ReturnToRoomGameObject;
        public UnityEngine.RectTransform ReturnToRoomRectTransform => this.m_ReturnToRoomRectTransform;
        public UnityEngine.GameObject StatusGameObject => this.m_StatusGameObject;
        public UnityEngine.RectTransform StatusRectTransform => this.m_StatusRectTransform;
        public UnityEngine.UI.UXText StatusUXText => this.m_StatusUXText;

#if UNITY_EDITOR
        [Sirenix.OdinInspector.OnInspectorGUI, Sirenix.OdinInspector.PropertyOrder(-99999), Sirenix.OdinInspector.ShowIf(nameof(HasMissingTargets))]
        private void DrawMissingTargetsWarning()
        {
            Sirenix.Utilities.Editor.SirenixEditorGUI.MessageBox("Binding targets contain missing references.", UnityEditor.MessageType.Warning);
        }

        private bool HasMissingTargets()
        {
            if (this.m_ReturnToRoomButton == null) return true;
            if (this.m_ReturnToRoomGameObject == null) return true;
            if (this.m_ReturnToRoomRectTransform == null) return true;
            if (this.m_StatusGameObject == null) return true;
            if (this.m_StatusRectTransform == null) return true;
            if (this.m_StatusUXText == null) return true;
            return false;
        }
#endif

    }
}
