// This is automatically generated by CodeBind. Please do not modify it.

namespace ET.Client
{
    public partial class MonoUIFormSurvivorLobby
    {
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("Binding Targets"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.Button m_JoinButton;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("Binding Targets"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.GameObject m_JoinGameObject;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("Binding Targets"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.Image m_JoinImage;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("Binding Targets"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.RectTransform m_JoinRectTransform;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("Binding Targets"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.GameObject m_RoomCodeGameObject;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("Binding Targets"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.Image m_RoomCodeImage;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("Binding Targets"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.InputField m_RoomCodeInputField;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("Binding Targets"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.RectTransform m_RoomCodeRectTransform;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("Binding Targets"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.Button m_StartButton;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("Binding Targets"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.GameObject m_StartGameObject;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("Binding Targets"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.Image m_StartImage;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("Binding Targets"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.RectTransform m_StartRectTransform;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("Binding Targets"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.GameObject m_StatusGameObject;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("Binding Targets"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.RectTransform m_StatusRectTransform;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("Binding Targets"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.UXText m_StatusUXText;

        public UnityEngine.UI.Button JoinButton => this.m_JoinButton;
        public UnityEngine.GameObject JoinGameObject => this.m_JoinGameObject;
        public UnityEngine.UI.Image JoinImage => this.m_JoinImage;
        public UnityEngine.RectTransform JoinRectTransform => this.m_JoinRectTransform;
        public UnityEngine.GameObject RoomCodeGameObject => this.m_RoomCodeGameObject;
        public UnityEngine.UI.Image RoomCodeImage => this.m_RoomCodeImage;
        public UnityEngine.UI.InputField RoomCodeInputField => this.m_RoomCodeInputField;
        public UnityEngine.RectTransform RoomCodeRectTransform => this.m_RoomCodeRectTransform;
        public UnityEngine.UI.Button StartButton => this.m_StartButton;
        public UnityEngine.GameObject StartGameObject => this.m_StartGameObject;
        public UnityEngine.UI.Image StartImage => this.m_StartImage;
        public UnityEngine.RectTransform StartRectTransform => this.m_StartRectTransform;
        public UnityEngine.GameObject StatusGameObject => this.m_StatusGameObject;
        public UnityEngine.RectTransform StatusRectTransform => this.m_StatusRectTransform;
        public UnityEngine.UI.UXText StatusUXText => this.m_StatusUXText;

#if UNITY_EDITOR
        [Sirenix.OdinInspector.OnInspectorGUI, Sirenix.OdinInspector.PropertyOrder(-99999), Sirenix.OdinInspector.ShowIf(nameof(HasMissingTargets))]
        private void DrawMissingTargetsWarning()
        {
            Sirenix.Utilities.Editor.SirenixEditorGUI.MessageBox("Binding targets contain missing references.", UnityEditor.MessageType.Warning);
        }

        private bool HasMissingTargets()
        {
            if (this.m_JoinButton == null) return true;
            if (this.m_JoinGameObject == null) return true;
            if (this.m_JoinImage == null) return true;
            if (this.m_JoinRectTransform == null) return true;
            if (this.m_RoomCodeGameObject == null) return true;
            if (this.m_RoomCodeImage == null) return true;
            if (this.m_RoomCodeInputField == null) return true;
            if (this.m_RoomCodeRectTransform == null) return true;
            if (this.m_StartButton == null) return true;
            if (this.m_StartGameObject == null) return true;
            if (this.m_StartImage == null) return true;
            if (this.m_StartRectTransform == null) return true;
            if (this.m_StatusGameObject == null) return true;
            if (this.m_StatusRectTransform == null) return true;
            if (this.m_StatusUXText == null) return true;
            return false;
        }
#endif

    }
}
