
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace ET
{
public sealed partial class DRAIConfig : Luban.BeanBase
{
    public DRAIConfig(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["AIConfigId"].IsNumber) { throw new SerializationException(); }  AIConfigId = _buf["AIConfigId"]; }
        { if(!_buf["Order"].IsNumber) { throw new SerializationException(); }  Order = _buf["Order"]; }
        { if(!_buf["Name"].IsString) { throw new SerializationException(); }  Name = _buf["Name"]; }
        { if(!_buf["Desc"].IsString) { throw new SerializationException(); }  Desc = _buf["Desc"]; }
        { var __json0 = _buf["NodeParams"]; if(!__json0.IsArray) { throw new SerializationException(); } NodeParams = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  NodeParams.Add(__v0); }   }
        PostInit();
    }

    public static DRAIConfig DeserializeDRAIConfig(JSONNode _buf)
    {
        return new DRAIConfig(_buf);
    }

    /// <summary>
    /// Id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 所属ai
    /// </summary>
    public readonly int AIConfigId;
    /// <summary>
    /// 此ai中的顺序
    /// </summary>
    public readonly int Order;
    /// <summary>
    /// 节点名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 节点参数
    /// </summary>
    public readonly System.Collections.Generic.List<int> NodeParams;
    public const int __ID__ = 1340429336;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
        PostResolve();
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "AIConfigId:" + AIConfigId + ","
        + "Order:" + Order + ","
        + "Name:" + Name + ","
        + "Desc:" + Desc + ","
        + "NodeParams:" + Luban.StringUtil.CollectionToString(NodeParams) + ","
        + "}";
    }

    partial void PostInit();
    partial void PostResolve();
}
}
