
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
public sealed partial class DRDemo : Luban.BeanBase
{
    public DRDemo(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Key = _buf.ReadString();
        PostInit();
    }

    public static DRDemo DeserializeDRDemo(ByteBuf _buf)
    {
        return new DRDemo(_buf);
    }

    public readonly int Id;
    /// <summary>
    /// 策划备注不导表
    /// </summary>
    public readonly string Key;
    public const int __ID__ = 2024637329;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        PostResolveRef();
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Key:" + Key + ","
        + "}";
    }

    partial void PostInit();
    partial void PostResolveRef();
}
}
