
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace ET
{
public sealed partial class DROneConfig : Luban.BeanBase
{
    public DROneConfig(JSONNode _buf) 
    {
        { if(!_buf["Test"].IsNumber) { throw new SerializationException(); }  Test = _buf["Test"]; }
        PostInit();
    }

    public static DROneConfig DeserializeDROneConfig(JSONNode _buf)
    {
        return new DROneConfig(_buf);
    }

    /// <summary>
    /// 匹配最大时间
    /// </summary>
    public readonly int Test;
    public const int __ID__ = -2019618726;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        PostResolve();
    }

    public override string ToString()
    {
        return "{ "
        + "Test:" + Test + ","
        + "}";
    }

    partial void PostInit();
    partial void PostResolve();
}
}
