
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
public sealed partial class DROneConfig : Luban.BeanBase
{
    /// <summary>
    /// 匹配最大时间
    /// </summary>
    public int Test;
    public const int __ID__ = -2019618726;
    public override int GetTypeId() => __ID__;

    public void Init(Tables tables)
    {
        PostInit();
        ResolveRef(tables);
    }

    public  void ResolveRef(Tables tables)
    {
        
    }

    public override string ToString()
    {
        return "{ "
        + "Test:" + Test + ","
        + "}";
    }

    partial void PostInit();
}
}
