
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
public partial class DTAIConfig
{
    private readonly Tables _tables;

    public DTAIConfig(Tables tables)
    {
        _tables = tables;
        _dataMap = new System.Collections.Generic.Dictionary<int, DRAIConfig>();
        PostConstructor();
        PostInit();
    }

    private readonly System.Collections.Generic.Dictionary<int, DRAIConfig> _dataMap;
    public System.Collections.Generic.List<int> KeyList { private set; get; }
    public DRAIConfig Get(int key) => TryGetValue(key, out var v) ? v : null;
    public DRAIConfig this[int key] => TryGetValue(key, out var v) ? v : null;

    // private bool InternalTryGetValue(int key, out DRAIConfig value);
    private bool TryGetValue(int key, out DRAIConfig value)
    {
        if(_dataMap.TryGetValue(key, out value))
        {
            return true;
        }
        if(InternalTryGetValue(key, out value))
        {
            _dataMap.Add(key, value);
            value.Init(_tables);
            return true;
        }
        value = default;
        return false;
    }


    partial void PostConstructor();
    partial void PostInit();
}
}
