
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
public partial class DTOneConfig
{
    private readonly Tables _tables;
    public DTOneConfig(Tables tables)
    {
        _tables = tables;
        PostConstructor();
        PostInit();
    }

    private DROneConfig _data;
    /// <summary>
    /// 匹配最大时间
    /// </summary>
    public int Test => _data.Test;

    partial void PostConstructor();
    partial void PostInit();
}
}
