
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
public partial class Tables
{
    public DTOneConfig DTOneConfig { private set; get; }
    public DTAIConfig DTAIConfig { private set; get; }
    public DTUnitConfig DTUnitConfig { private set; get; }
    public DTDemo DTDemo { private set; get; }

    public Tables()
    {
        DTOneConfig = new DTOneConfig(this);
        DTAIConfig = new DTAIConfig(this);
        DTUnitConfig = new DTUnitConfig(this);
        DTDemo = new DTDemo(this);

        PostInit();
    }

    partial void PostInit();
}
}

