//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace ET
{
public partial class Tables
{
    public DTOneConfig DTOneConfig { private set; get; }
    public DTAIConfig DTAIConfig { private set; get; }
    public DTUnitConfig DTUnitConfig { private set; get; }
    public DTDemo DTDemo { private set; get; }
    private Dictionary<string, IDataTable> _tables;
    public IEnumerable<IDataTable> DataTables => _tables.Values;
    public IDataTable GetDataTable(string tableName) => _tables.TryGetValue(tableName, out var v) ? v : null;

    public async Task LoadAsync(System.Func<string, Task<ByteBuf>> loader)
    {
        TablesMemory.BeginRecord();

        _tables = new Dictionary<string, IDataTable>();
        List<Task> loadTasks = new List<Task>();
        DTOneConfig = new DTOneConfig(() => loader("dtoneconfig"));
        loadTasks.Add(DTOneConfig.LoadAsync());
        _tables.Add("DTOneConfig", DTOneConfig);
        DTAIConfig = new DTAIConfig(() => loader("dtaiconfig"));
        loadTasks.Add(DTAIConfig.LoadAsync());
        _tables.Add("DTAIConfig", DTAIConfig);
        DTUnitConfig = new DTUnitConfig(() => loader("dtunitconfig"));
        loadTasks.Add(DTUnitConfig.LoadAsync());
        _tables.Add("DTUnitConfig", DTUnitConfig);
        DTDemo = new DTDemo(() => loader("dtdemo"));
        loadTasks.Add(DTDemo.LoadAsync());
        _tables.Add("DTDemo", DTDemo);

        await Task.WhenAll(loadTasks);

        Refresh();

        TablesMemory.EndRecord();
    }

    public void Refresh()
    {
        PostInit();
        DTOneConfig.Resolve(_tables); 
        DTAIConfig.Resolve(_tables); 
        DTUnitConfig.Resolve(_tables); 
        DTDemo.Resolve(_tables); 
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        DTOneConfig.TranslateText(translator); 
        DTAIConfig.TranslateText(translator); 
        DTUnitConfig.TranslateText(translator); 
        DTDemo.TranslateText(translator); 
    }

    partial void PostInit();
    partial void PostResolve();
}
}