// This is automatically generated by CodeBind. Please do not modify it.

namespace ET.Client
{
    public partial class MonoSurvivorSpriteEntity
    {
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("Binding Targets"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.GameObject m_DamageTextGameObject;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("Binding Targets"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.RectTransform m_DamageTextRectTransform;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("Binding Targets"), Sirenix.OdinInspector.ReadOnly]
        private TMPro.TextMeshPro m_DamageTextTextMeshPro;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("Binding Targets"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.GameObject m_FillGameObject;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("Binding Targets"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.SpriteRenderer m_FillSpriteRenderer;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("Binding Targets"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.Transform m_FillTransform;

        public UnityEngine.GameObject DamageTextGameObject => this.m_DamageTextGameObject;
        public UnityEngine.RectTransform DamageTextRectTransform => this.m_DamageTextRectTransform;
        public TMPro.TextMeshPro DamageTextTextMeshPro => this.m_DamageTextTextMeshPro;
        public UnityEngine.GameObject FillGameObject => this.m_FillGameObject;
        public UnityEngine.SpriteRenderer FillSpriteRenderer => this.m_FillSpriteRenderer;
        public UnityEngine.Transform FillTransform => this.m_FillTransform;

#if UNITY_EDITOR
        [Sirenix.OdinInspector.OnInspectorGUI, Sirenix.OdinInspector.PropertyOrder(-99999), Sirenix.OdinInspector.ShowIf(nameof(HasMissingTargets))]
        private void DrawMissingTargetsWarning()
        {
            Sirenix.Utilities.Editor.SirenixEditorGUI.MessageBox("Binding targets contain missing references.", UnityEditor.MessageType.Warning);
        }

        private bool HasMissingTargets()
        {
            if (this.m_DamageTextGameObject == null) return true;
            if (this.m_DamageTextRectTransform == null) return true;
            if (this.m_DamageTextTextMeshPro == null) return true;
            if (this.m_FillGameObject == null) return true;
            if (this.m_FillSpriteRenderer == null) return true;
            if (this.m_FillTransform == null) return true;
            return false;
        }
#endif

    }
}
