//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace editor.cfg.test
{

public abstract partial class Shape :  Bright.Config.EditorBeanBase 
{
    public Shape()
    {
    }


    public static Shape LoadJsonShape(SimpleJSON.JSONNode _json)
    {
        string type = _json["$type"];
        Shape obj;
        switch (type)
        {
            case "test.Circle":   
            case "Circle":obj = new test.Circle(); break;
            case "test.Rectangle":   
            case "Rectangle":obj = new test.Rectangle(); break;
            default: throw new SerializationException();
        }
        obj.LoadJson((SimpleJSON.JSONObject)_json);
        return obj;
    }
        
    public static void SaveJsonShape(Shape _obj, SimpleJSON.JSONNode _json)
    {
        _json["$type"] = _obj.GetType().Name;
        _obj.SaveJson((SimpleJSON.JSONObject)_json);
    }

}
}
