//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace editor.cfg.test
{

/// <summary>
/// 这是个测试excel结构
/// </summary>
public sealed partial class TestExcelBean2 :  Bright.Config.EditorBeanBase 
{
    public TestExcelBean2()
    {
            Y2 = "";
    }

    public override void LoadJson(SimpleJSON.JSONObject _json)
    {
        { 
            var _fieldJson = _json["y1"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  Y1 = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["y2"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  Y2 = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["y3"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  Y3 = _fieldJson;
            }
        }
        
    }

    public override void SaveJson(SimpleJSON.JSONObject _json)
    {
        _json["$type"] = "test.TestExcelBean2";
        {
            _json["y1"] = new JSONNumber(Y1);
        }
        {

            if (Y2 == null) { throw new System.ArgumentNullException(); }
            _json["y2"] = new JSONString(Y2);
        }
        {
            _json["y3"] = new JSONNumber(Y3);
        }
    }

    public static TestExcelBean2 LoadJsonTestExcelBean2(SimpleJSON.JSONNode _json)
    {
        TestExcelBean2 obj = new test.TestExcelBean2();
        obj.LoadJson((SimpleJSON.JSONObject)_json);
        return obj;
    }
        
    public static void SaveJsonTestExcelBean2(TestExcelBean2 _obj, SimpleJSON.JSONNode _json)
    {
        _obj.SaveJson((SimpleJSON.JSONObject)_json);
    }

    /// <summary>
    /// 最高品质
    /// </summary>
    public int Y1 { get; set; }

    /// <summary>
    /// 黑色的
    /// </summary>
    public string Y2 { get; set; }

    /// <summary>
    /// 蓝色的
    /// </summary>
    public float Y3 { get; set; }

}
}
