//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace editor.cfg.test
{

/// <summary>
/// 这是个测试excel结构
/// </summary>
public sealed partial class TestExcelBean1 :  Bright.Config.EditorBeanBase 
{
    public TestExcelBean1()
    {
            X2 = "";
    }

    public override void LoadJson(SimpleJSON.JSONObject _json)
    {
        { 
            var _fieldJson = _json["x1"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  X1 = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["x2"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  X2 = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["x3"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  X3 = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["x4"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  X4 = _fieldJson;
            }
        }
        
    }

    public override void SaveJson(SimpleJSON.JSONObject _json)
    {
        _json["$type"] = "test.TestExcelBean1";
        {
            _json["x1"] = new JSONNumber(X1);
        }
        {

            if (X2 == null) { throw new System.ArgumentNullException(); }
            _json["x2"] = new JSONString(X2);
        }
        {
            _json["x3"] = new JSONNumber(X3);
        }
        {
            _json["x4"] = new JSONNumber(X4);
        }
    }

    public static TestExcelBean1 LoadJsonTestExcelBean1(SimpleJSON.JSONNode _json)
    {
        TestExcelBean1 obj = new test.TestExcelBean1();
        obj.LoadJson((SimpleJSON.JSONObject)_json);
        return obj;
    }
        
    public static void SaveJsonTestExcelBean1(TestExcelBean1 _obj, SimpleJSON.JSONNode _json)
    {
        _obj.SaveJson((SimpleJSON.JSONObject)_json);
    }

    /// <summary>
    /// 最高品质
    /// </summary>
    public int X1 { get; set; }

    /// <summary>
    /// 黑色的
    /// </summary>
    public string X2 { get; set; }

    /// <summary>
    /// 蓝色的
    /// </summary>
    public int X3 { get; set; }

    /// <summary>
    /// 最差品质
    /// </summary>
    public float X4 { get; set; }

}
}
