// This is automatically generated by CodeBind. Please do not modify it.

namespace Game
{
    public partial class RuntimeInspectorForm
    {
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private StateController.StateControllerMono m_RootStateControllerMono;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.Button m_CloseButton;


        public StateController.StateControllerMono RootStateControllerMono => m_RootStateControllerMono;
        public UnityEngine.UI.Button CloseButton => m_CloseButton;


        private StateController.StateControllerData m_RootLayoutStateControllerData;
        public StateController.StateControllerData RootLayoutStateControllerData => m_RootLayoutStateControllerData ??= RootStateControllerMono.GetData("Layout");
        public static class RootLayoutStateName
        {
            public const string Vertical = "Vertical";
            public const string Horizontal = "Horizontal";
        }

    }
}
