//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace cfg.ET
{
public sealed partial class DRStartZoneConfig :  Bright.Config.BeanBase 
{
    public DRStartZoneConfig(ByteBuf _buf) 
    {
        StartConfig = _buf.ReadString();
        Id = _buf.ReadInt();
        DBConnection = _buf.ReadString();
        DBName = _buf.ReadString();
        Desc = _buf.ReadString();
        PostInit();
    }

    public static DRStartZoneConfig DeserializeDRStartZoneConfig(ByteBuf _buf)
    {
        return new ET.DRStartZoneConfig(_buf);
    }

    /// <summary>
    /// 开启类型
    /// </summary>
    public string StartConfig { get; private set; }
    /// <summary>
    /// Id
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 数据库地址
    /// </summary>
    public string DBConnection { get; private set; }
    /// <summary>
    /// 数据库名
    /// </summary>
    public string DBName { get; private set; }
    /// <summary>
    /// 说明
    /// </summary>
    public string Desc { get; private set; }

    public const int __ID__ = -816615901;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "StartConfig:" + StartConfig + ","
        + "Id:" + Id + ","
        + "DBConnection:" + DBConnection + ","
        + "DBName:" + DBName + ","
        + "Desc:" + Desc + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}