//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET.Editor.test
{
    [System.Flags]
    public enum AccessFlag
    {
        WRITE = 1,
        READ = 2,
        TRUNCATE = 4,
        NEW = 8,
        /// <summary>
        /// 位标记使用示例
        /// </summary>
        READ_WRITE = WRITE|READ,
    }

    public static partial class AccessFlag_Metadata
    {
        public static readonly Bright.Config.EditorEnumItemInfo WRITE = new Bright.Config.EditorEnumItemInfo("WRITE", "", 1, "");
        public static readonly Bright.Config.EditorEnumItemInfo READ = new Bright.Config.EditorEnumItemInfo("READ", "", 2, "");
        public static readonly Bright.Config.EditorEnumItemInfo TRUNCATE = new Bright.Config.EditorEnumItemInfo("TRUNCATE", "", 4, "");
        public static readonly Bright.Config.EditorEnumItemInfo NEW = new Bright.Config.EditorEnumItemInfo("NEW", "", 8, "");
        public static readonly Bright.Config.EditorEnumItemInfo READ_WRITE = new Bright.Config.EditorEnumItemInfo("READ_WRITE", "", 3, "位标记使用示例");

        private static readonly System.Collections.Generic.List<Bright.Config.EditorEnumItemInfo> __items = new System.Collections.Generic.List<Bright.Config.EditorEnumItemInfo>
        {
            WRITE,
            READ,
            TRUNCATE,
            NEW,
            READ_WRITE,
        };

        public static System.Collections.Generic.List<Bright.Config.EditorEnumItemInfo> GetItems() => __items;

        public static Bright.Config.EditorEnumItemInfo GetByName(string name)
        {
            return __items.Find(c => c.Name == name);
        }

        public static Bright.Config.EditorEnumItemInfo GetByNameOrAlias(string name)
        {
            return __items.Find(c => c.Name == name || c.Alias == name);
        }

        public static Bright.Config.EditorEnumItemInfo GetByValue(int value)
        {
            return __items.Find(c => c.Value == value);
        }
    }

}
