
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
public sealed partial class DRAIConfig : Luban.BeanBase
{
    /// <summary>
    /// Id
    /// </summary>
    public int Id;
    /// <summary>
    /// 所属ai
    /// </summary>
    public int AIConfigId;
    /// <summary>
    /// 此ai中的顺序
    /// </summary>
    public int Order;
    /// <summary>
    /// 节点名字
    /// </summary>
    public string Name;
    /// <summary>
    /// 描述
    /// </summary>
    public string Desc;
    /// <summary>
    /// 节点参数
    /// </summary>
    public System.Collections.Generic.List<int> NodeParams;
    public const int __ID__ = 1340429336;
    public override int GetTypeId() => __ID__;

    public void Init(Tables tables)
    {
        PostInit();
        ResolveRef(tables);
    }

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "AIConfigId:" + AIConfigId + ","
        + "Order:" + Order + ","
        + "Name:" + Name + ","
        + "Desc:" + Desc + ","
        + "NodeParams:" + Luban.StringUtil.CollectionToString(NodeParams) + ","
        + "}";
    }

    partial void PostInit();
}
}
