
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
public sealed partial class DRAIConfig : Luban.BeanBase
{
    public DRAIConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        AIConfigId = _buf.ReadInt();
        Order = _buf.ReadInt();
        Name = _buf.ReadString();
        Desc = _buf.ReadString();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);NodeParams = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); NodeParams.Add(_e0);}}
        PostInit();
    }

    public static DRAIConfig DeserializeDRAIConfig(ByteBuf _buf)
    {
        return new DRAIConfig(_buf);
    }

    /// <summary>
    /// Id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 所属ai
    /// </summary>
    public readonly int AIConfigId;
    /// <summary>
    /// 此ai中的顺序
    /// </summary>
    public readonly int Order;
    /// <summary>
    /// 节点名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 节点参数
    /// </summary>
    public readonly System.Collections.Generic.List<int> NodeParams;
    public const int __ID__ = 1340429336;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        PostResolveRef();
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "AIConfigId:" + AIConfigId + ","
        + "Order:" + Order + ","
        + "Name:" + Name + ","
        + "Desc:" + Desc + ","
        + "NodeParams:" + Luban.StringUtil.CollectionToString(NodeParams) + ","
        + "}";
    }

    partial void PostInit();
    partial void PostResolveRef();
}
}
