
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
public sealed partial class DRDemo : Luban.BeanBase
{
    public int Id;
    /// <summary>
    /// 策划备注不导表
    /// </summary>
    public string Key;
    public const int __ID__ = 2024637329;
    public override int GetTypeId() => __ID__;

    public void Init(Tables tables)
    {
        PostInit();
        ResolveRef(tables);
    }

    public  void ResolveRef(Tables tables)
    {
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Key:" + Key + ","
        + "}";
    }

    partial void PostInit();
}
}
