
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
public sealed partial class DRStartZoneConfig : Luban.BeanBase
{
    /// <summary>
    /// 开启类型
    /// </summary>
    public string StartConfig;
    /// <summary>
    /// Id
    /// </summary>
    public int Id;
    /// <summary>
    /// 数据库地址
    /// </summary>
    public string DBConnection;
    /// <summary>
    /// 数据库名
    /// </summary>
    public string DBName;
    /// <summary>
    /// 说明
    /// </summary>
    public string Desc;
    public const int __ID__ = -1835667038;
    public override int GetTypeId() => __ID__;

    public void Init(Tables tables)
    {
        PostInit();
        ResolveRef(tables);
    }

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "StartConfig:" + StartConfig + ","
        + "Id:" + Id + ","
        + "DBConnection:" + DBConnection + ","
        + "DBName:" + DBName + ","
        + "Desc:" + Desc + ","
        + "}";
    }

    partial void PostInit();
}
}
