
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace ET
{
public sealed partial class DRStartSceneConfig : Luban.BeanBase
{
    public DRStartSceneConfig(JSONNode _buf) 
    {
        { if(!_buf["StartConfig"].IsString) { throw new SerializationException(); }  StartConfig = _buf["StartConfig"]; }
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["Process"].IsNumber) { throw new SerializationException(); }  Process = _buf["Process"]; }
        { if(!_buf["Zone"].IsNumber) { throw new SerializationException(); }  Zone = _buf["Zone"]; }
        { if(!_buf["SceneType"].IsString) { throw new SerializationException(); }  SceneType = _buf["SceneType"]; }
        { if(!_buf["Name"].IsString) { throw new SerializationException(); }  Name = _buf["Name"]; }
        { if(!_buf["Port"].IsNumber) { throw new SerializationException(); }  Port = _buf["Port"]; }
        PostInit();
    }

    public static DRStartSceneConfig DeserializeDRStartSceneConfig(JSONNode _buf)
    {
        return new DRStartSceneConfig(_buf);
    }

    /// <summary>
    /// 开启类型
    /// </summary>
    public readonly string StartConfig;
    /// <summary>
    /// Id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 所属进程
    /// </summary>
    public readonly int Process;
    /// <summary>
    /// 所属区
    /// </summary>
    public readonly int Zone;
    /// <summary>
    /// 类型
    /// </summary>
    public readonly string SceneType;
    /// <summary>
    /// 名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 外网端口
    /// </summary>
    public readonly int Port;
    public const int __ID__ = 1720259034;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
        
        PostResolve();
    }

    public override string ToString()
    {
        return "{ "
        + "StartConfig:" + StartConfig + ","
        + "Id:" + Id + ","
        + "Process:" + Process + ","
        + "Zone:" + Zone + ","
        + "SceneType:" + SceneType + ","
        + "Name:" + Name + ","
        + "Port:" + Port + ","
        + "}";
    }

    partial void PostInit();
    partial void PostResolve();
}
}
