
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
public sealed partial class DRStartSceneConfig : Luban.BeanBase
{
    public DRStartSceneConfig(ByteBuf _buf) 
    {
        StartConfig = _buf.ReadString();
        Id = _buf.ReadInt();
        Process = _buf.ReadInt();
        Zone = _buf.ReadInt();
        SceneType = _buf.ReadString();
        Name = _buf.ReadString();
        Port = _buf.ReadInt();
        PostInit();
    }

    public static DRStartSceneConfig DeserializeDRStartSceneConfig(ByteBuf _buf)
    {
        return new DRStartSceneConfig(_buf);
    }

    /// <summary>
    /// 开启类型
    /// </summary>
    public readonly string StartConfig;
    /// <summary>
    /// Id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 所属进程
    /// </summary>
    public readonly int Process;
    /// <summary>
    /// 所属区
    /// </summary>
    public readonly int Zone;
    /// <summary>
    /// 类型
    /// </summary>
    public readonly string SceneType;
    /// <summary>
    /// 名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 外网端口
    /// </summary>
    public readonly int Port;
    public const int __ID__ = 1720259034;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        PostResolveRef();
    }

    public override string ToString()
    {
        return "{ "
        + "StartConfig:" + StartConfig + ","
        + "Id:" + Id + ","
        + "Process:" + Process + ","
        + "Zone:" + Zone + ","
        + "SceneType:" + SceneType + ","
        + "Name:" + Name + ","
        + "Port:" + Port + ","
        + "}";
    }

    partial void PostInit();
    partial void PostResolveRef();
}
}
