
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
public sealed partial class DRUnitConfig : Luban.BeanBase
{
    /// <summary>
    /// Id
    /// </summary>
    public int Id;
    /// <summary>
    /// Type
    /// </summary>
    public int Type;
    /// <summary>
    /// 名字
    /// </summary>
    public string Name;
    /// <summary>
    /// 描述
    /// </summary>
    public string Desc;
    /// <summary>
    /// 位置
    /// </summary>
    public int Position;
    /// <summary>
    /// 身高
    /// </summary>
    public int Height;
    /// <summary>
    /// 体重
    /// </summary>
    public int Weight;
    public const int __ID__ = -1701961452;
    public override int GetTypeId() => __ID__;

    public void Init(Tables tables)
    {
        PostInit();
        ResolveRef(tables);
    }

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Type:" + Type + ","
        + "Name:" + Name + ","
        + "Desc:" + Desc + ","
        + "Position:" + Position + ","
        + "Height:" + Height + ","
        + "Weight:" + Weight + ","
        + "}";
    }

    partial void PostInit();
}
}
