
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
public sealed partial class DRUnitConfig : Luban.BeanBase
{
    public DRUnitConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Type = _buf.ReadInt();
        Name = _buf.ReadString();
        Desc = _buf.ReadString();
        Position = _buf.ReadInt();
        Height = _buf.ReadInt();
        Weight = _buf.ReadInt();
        PostInit();
    }

    public static DRUnitConfig DeserializeDRUnitConfig(ByteBuf _buf)
    {
        return new DRUnitConfig(_buf);
    }

    /// <summary>
    /// Id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// Type
    /// </summary>
    public readonly int Type;
    /// <summary>
    /// 名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 位置
    /// </summary>
    public readonly int Position;
    /// <summary>
    /// 身高
    /// </summary>
    public readonly int Height;
    /// <summary>
    /// 体重
    /// </summary>
    public readonly int Weight;
    public const int __ID__ = -1701961452;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        PostResolveRef();
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Type:" + Type + ","
        + "Name:" + Name + ","
        + "Desc:" + Desc + ","
        + "Position:" + Position + ","
        + "Height:" + Height + ","
        + "Weight:" + Weight + ","
        + "}";
    }

    partial void PostInit();
    partial void PostResolveRef();
}
}
