
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace ET
{
public partial class DTOneConfig : IDataTable
{

    private DROneConfig _data;
    public DROneConfig Data => _data;
    private readonly System.Func<Cysharp.Threading.Tasks.UniTask<JSONNode>> _loadFunc;

    public DTOneConfig(System.Func<Cysharp.Threading.Tasks.UniTask<JSONNode>> loadFunc)
    {
        _loadFunc = loadFunc;
    }

    public async Cysharp.Threading.Tasks.UniTask LoadAsync()
    {
        JSONNode _json = await _loadFunc();
        int n = _json.Count;
        if (n != 1) throw new SerializationException("table mode=one, but size != 1");
        { if(!_json[0].IsObject) { throw new SerializationException(); }  _data = DROneConfig.DeserializeDROneConfig(_json[0]);  }
    }

    /// <summary>
    /// 匹配最大时间
    /// </summary>
    public long MaxMatchTime => _data.MaxMatchTime;
    /// <summary>
    /// 匹配最大时间
    /// </summary>
    public int Test => _data.Test;

    public void ResolveRef(Tables tables)
    {
        _data.ResolveRef(tables);
        PostResolve();
    }

    partial void PostInit();
    partial void PostResolve();
}
}

