
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
public partial class DTStartSceneConfig : IDataTable
{
    private System.Collections.Generic.List<DRStartSceneConfig> _dataList;
    private System.Collections.Generic.Dictionary<(string, int), DRStartSceneConfig> _dataMapUnion;
    private readonly System.Func<Cysharp.Threading.Tasks.UniTask<ByteBuf>> _loadFunc;

    public DTStartSceneConfig(System.Func<Cysharp.Threading.Tasks.UniTask<ByteBuf>> loadFunc)
    {
        _loadFunc = loadFunc;
    }

    public async Cysharp.Threading.Tasks.UniTask LoadAsync()
    {
        ByteBuf _buf = await _loadFunc();
        int n = _buf.ReadSize();
        if(_dataList == null)
        {
            _dataList = new System.Collections.Generic.List<DRStartSceneConfig>(n);
        }
        else
        {
            _dataList.Clear();
        }
        for(int i = n ; i > 0 ; --i)
        {
            DRStartSceneConfig _v;
            _v = global::ET.DRStartSceneConfig.DeserializeDRStartSceneConfig(_buf);
            _dataList.Add(_v);
        }
        if(_dataMapUnion == null)
        {
            _dataMapUnion = new System.Collections.Generic.Dictionary<(string, int), DRStartSceneConfig>(n);
        }
        else
        {
            _dataMapUnion.Clear();
        }
        foreach(var _v in _dataList)
        {
            _dataMapUnion.Add((_v.StartConfig, _v.Id), _v);
        }
        PostInit();
    }

    public System.Collections.Generic.List<DRStartSceneConfig> DataList => _dataList;
    public DRStartSceneConfig Get(string StartConfig, int Id) => _dataMapUnion.TryGetValue((StartConfig, Id), out DRStartSceneConfig __v) ? __v : null;

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
        PostResolveRef();
    }

    partial void PostInit();
    partial void PostResolveRef();
}
}
