
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
public partial class DTStartProcessConfig
{
    private readonly Tables _tables;
    public DTStartProcessConfig(Tables tables)
    {
        _tables = tables;
        _dataMapUnion = new System.Collections.Generic.Dictionary<(string, int), DRStartProcessConfig>();
        PostConstructor();
        PostInit();
    }

    private System.Collections.Generic.Dictionary<(string, int), DRStartProcessConfig> _dataMapUnion;
    public System.Collections.Generic.List<(string, int)> KeyList { private set; get; }
    public DRStartProcessConfig Get((string, int) key) => TryGetValue(key, out DRStartProcessConfig v) ? v : null;
    public DRStartProcessConfig Get(string StartConfig, int Id) => Get((StartConfig, Id));

    // partial bool InternalTryGetValue((string, int) key, out DRStartProcessConfig value);
    private bool TryGetValue((string, int) key, out DRStartProcessConfig value)
    {
        if(_dataMapUnion.TryGetValue(key, out value))
        {
            return true;
        }
        if(InternalTryGetValue(key, out value))
        {
            _dataMapUnion.Add(key, value);
            value.Init(_tables);
            return true;
        }
        value = default;
        return false;
    }
    

    partial void PostConstructor();
    partial void PostInit();
}
}
