
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
public partial class DTStartZoneConfig : IDataTable
{
    private readonly System.Collections.Generic.List<DRStartZoneConfig> _dataList;
    private System.Collections.Generic.Dictionary<(string, int), DRStartZoneConfig> _dataMapUnion;
    private readonly System.Func<Cysharp.Threading.Tasks.UniTask<ByteBuf>> _loadFunc;

    public DTStartZoneConfig(System.Func<Cysharp.Threading.Tasks.UniTask<ByteBuf>> loadFunc)
    {
        _loadFunc = loadFunc;
        _dataList = new System.Collections.Generic.List<DRStartZoneConfig>();
         _dataMapUnion = new System.Collections.Generic.Dictionary<(string, int), DRStartZoneConfig>();
    }

    public async Cysharp.Threading.Tasks.UniTask LoadAsync()
    {
        ByteBuf _buf = await _loadFunc();
        _dataList.Clear();
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            DRStartZoneConfig _v;
            _v = DRStartZoneConfig.DeserializeDRStartZoneConfig(_buf);
            _dataList.Add(_v);
        }
        _dataMapUnion.Clear();
        foreach(var _v in _dataList)
        {
            _dataMapUnion.Add((_v.StartConfig, _v.Id), _v);
        }
        PostInit();
    }

    public System.Collections.Generic.List<DRStartZoneConfig> DataList => _dataList;
    public DRStartZoneConfig Get(string StartConfig, int Id) => _dataMapUnion.TryGetValue((StartConfig, Id), out DRStartZoneConfig __v) ? __v : null;

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
        PostResolveRef();
    }

    partial void PostInit();
    partial void PostResolveRef();
}
}
