//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Threading.Tasks;



namespace Game
{ 
public partial class Tables
{
    public DTUIForm DTUIForm {private set; get; }
    public DTEntity DTEntity {private set; get; }
    public DTScene DTScene {private set; get; }
    public DTSound DTSound {private set; get; }
    public DTUISound DTUISound {private set; get; }
    public DTMusic DTMusic {private set; get; }
    public DTOneConfig DTOneConfig {private set; get; }

    public async Task LoadAsync(System.Func<string, Task<ByteBuf>> loader)
    {
        var tables = new System.Collections.Generic.Dictionary<string, object>();
        DTUIForm = new DTUIForm(await loader("dtuiform")); 
        tables.Add("DTUIForm", DTUIForm);
        DTEntity = new DTEntity(await loader("dtentity")); 
        tables.Add("DTEntity", DTEntity);
        DTScene = new DTScene(await loader("dtscene")); 
        tables.Add("DTScene", DTScene);
        DTSound = new DTSound(await loader("dtsound")); 
        tables.Add("DTSound", DTSound);
        DTUISound = new DTUISound(await loader("dtuisound")); 
        tables.Add("DTUISound", DTUISound);
        DTMusic = new DTMusic(await loader("dtmusic")); 
        tables.Add("DTMusic", DTMusic);
        DTOneConfig = new DTOneConfig(await loader("dtoneconfig")); 
        tables.Add("DTOneConfig", DTOneConfig);

        PostInit();
        DTUIForm.Resolve(tables); 
        DTEntity.Resolve(tables); 
        DTScene.Resolve(tables); 
        DTSound.Resolve(tables); 
        DTUISound.Resolve(tables); 
        DTMusic.Resolve(tables); 
        DTOneConfig.Resolve(tables); 
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        DTUIForm.TranslateText(translator); 
        DTEntity.TranslateText(translator); 
        DTScene.TranslateText(translator); 
        DTSound.TranslateText(translator); 
        DTUISound.TranslateText(translator); 
        DTMusic.TranslateText(translator); 
        DTOneConfig.TranslateText(translator); 
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}